language: java

env:
  global:
    - PROTOBUF_VERSION=3.6.1
    # - PROTOC_GEN_TS_PATH="./node_modules/.bin/protoc-gen-ts"
    - PROTOC_GEN_TS_PATH="/usr/local/lib/node_modules/ts-protoc-gen/bin/protoc-gen-ts"
    - TS_OUT_DIR="./target/generated/ts"
    - JAVA_OUT_DIR="./target/generated/java"
    - PATH=$PATH:~/protobuf-${PROTOBUF_VERSION}/src
cache:
  directories:
    - /home/travis/protobuf-${PROTOBUF_VERSION}

before_install:
  - "[[ -z \"${FORCE_PROTOBUF_INSTALL}\" ]] || rm -rf protobuf-${PROTOBUF_VERSION}"
  - "[[ -d \"protobuf-${PROTOBUF_VERSION}\" ]] || ./install-protobuf.sh"
  - npm install -g ts-protoc-gen

script:
  - echo "Running the script!"
  - mkdir -p $JAVA_OUT_DIR $TS_OUT_DIR
  # Generating TypeScript definitions
  - protoc --plugin="protoc-gen-ts=${PROTOC_GEN_TS_PATH}" --js_out="import_style=commonjs,binary:${TS_OUT_DIR}" --ts_out="service=true:${TS_OUT_DIR}" ./library/person.proto
  # Generating Java classes
  - protoc --proto_path=./library --java_out=${JAVA_OUT_DIR} ./library/*.proto
  - ls -l ${TS_OUT_DIR}
