language: java

env:
  global:
    - PROTOBUF_VERSION=3.6.1

cache:
  directories:
    - /home/travis/protobuf-${PROTOBUF_VERSION}

before_install:
  - if [ ! -d protobuf-${PROTOBUF_VERSION} ]; then ./install-protobuf.sh; fi

script:
  - echo "Running the script!"
  - protoc --proto_path=livrary --java_out=build/gen src/org.finos.fo