language: java

env:
  global:
    - PROTOBUF_VERSION=3.6.1
    # TODO - this should be local, ie ./node_modules/.bin/protoc-gen-ts,
    # but needs a package.json devDependency definition
    # This is what works on Docker (ubuntu:latest, see README.md)
    # - PROTOC_GEN_TS_PATH="/usr/local/lib/node_modules/ts-protoc-gen/bin/protoc-gen-ts"
    # This is what works in Travis CI
    - PROTOC_GEN_TS_PATH="/home/travis/.nvm/versions/node/v8.9.1/bin/protoc-gen-ts -> /home/travis/.nvm/versions/node/v8.9.1/lib/node_modules/ts-protoc-gen/bin/protoc-gen-ts"
    - TS_OUT_DIR="./target/generated/ts"
    - C_OUT_DIR="./target/generated/c"
    - JAVA_OUT_DIR="./target/generated/java"
    - PATH=$PATH:~/protobuf-${PROTOBUF_VERSION}/src
cache:
  directories:
    - /home/travis/protobuf-${PROTOBUF_VERSION}

before_install:
  - "[[ -z \"${FORCE_PROTOBUF_INSTALL}\" ]] || rm -rf protobuf-${PROTOBUF_VERSION} ; echo 'Deleted Protobuf ${PROTOBUF_VERSION} installation'"
  - "[[ -d \"protobuf-${PROTOBUF_VERSION}\" ]] || ./install-protobuf.sh"
  - npm install -g ts-protoc-gen

script:
  - echo "Running the script!"
  - mkdir -p $JAVA_OUT_DIR $TS_OUT_DIR $C_OUT_DIR
  # Generating TypeScript definitions
  - protoc --plugin="protoc-gen-ts=${PROTOC_GEN_TS_PATH}" --js_out="import_style=commonjs,binary:${TS_OUT_DIR}" --ts_out="service=true:${TS_OUT_DIR}" ./library/person.proto
  # Generating Java classes
  - protoc --proto_path=./library --java_out=${JAVA_OUT_DIR} ./library/*.proto
  - ls -l ${TS_OUT_DIR}
  # Generating C (TODO - plugin needs to be compiled)
  # - protoc --c_out=${C_OUT_DIR} ./library/*.proto
