language: java

node_js:
  - "8.9.1"

go:
  - "1.10"

env:
  global:
    - PROTOBUF_VERSION=3.6.1
    # Using protobufjs now, see tojs and tots npm scripts
    # - PROTOC_GEN_TS_PATH="/home/travis/.nvm/versions/node/v8.9.1/bin/protoc-gen-ts"
    - PROTOC_GEN_DOCS_PATH="/root/go/bin/protoc-gen-doc"
    - TS_OUT_DIR="./target/generated/ts"
    - C_OUT_DIR="./target/generated/c"
    - JAVA_OUT_DIR="./target/generated/java"
    - PATH=$PATH:~/protobuf-${PROTOBUF_VERSION}/src
    - PROTOC_CMD_PREFIX="protoc --proto_path=./proto"
    - PROTOBUF_SRC="./proto/*.proto"

cache:
  directories:
    - /home/travis/protobuf-${PROTOBUF_VERSION}

before_install:
  - go get -u github.com/pseudomuto/protoc-gen-doc/cmd/protoc-gen-doc
  - "[[ -z \"${FORCE_PROTOBUF_INSTALL}\" ]] || rm -rf protobuf-${PROTOBUF_VERSION} ; echo 'Deleted Protobuf ${PROTOBUF_VERSION} installation'"
  - "[[ -d \"protobuf-${PROTOBUF_VERSION}\" ]] || ./install-protobuf.sh"
  # Using protobufjs now, see tojs and tots npm scripts
  # - npm install -g ts-protoc-gen
  - npm install
  - npm run tojs
  - npm run tots
  - npm run sample

script:
  - mkdir -p $JAVA_OUT_DIR $TS_OUT_DIR $C_OUT_DIR
  # Generating Java classes
  - ${PROTOC_CMD_PREFIX} --java_out=${JAVA_OUT_DIR} ${PROTOBUF_SRC}
  # Generating Markdown documentation
  - ./build-docs.sh
  # Generating C (TODO - plugin needs to be compiled)
  # - protoc --c_out=${C_OUT_DIR} ./proto/*.proto
  # protoc-gen-ts was deprecated in favour of protobufjs
  # - ${PROTOC_CMD_PREFIX} --plugin="protoc-gen-ts=${PROTOC_GEN_TS_PATH}" --js_out="import_style=commonjs,binary:${TS_OUT_DIR}" --ts_out="service=true:${TS_OUT_DIR}" ${PROTOBUF_SRC}

# NEXT: deployment stages to
# 1. push html on gh-pages
# 2. package generated js and ts code into NPM
# 3. package generated .java code into JAR file, to install in Maven Central
# 4. publish C++/C# code in NuGet
