language: java

env:
  global:
    - PROTOBUF_VERSION=3.6.1

cache:
  directories:
    - /home/travis/protobuf-${PROTOBUF_VERSION}

before_install:
  - "[[ -d protobuf-${PROTOBUF_VERSION} ]] || ./install-protobuf.sh"

script:
  - echo "Running the script!"
  - mkdir -p target/generated
  - protoc --proto_path=library --java_out=target/generated
