// This class demoes how to consume the FINOS FO objects
// To check the generated code, open output-samples/model.js
// and model.d.ts

// Target folder is generated by the Travis build,
// check .travis.yml
import { org } from "./target/model.js";

let contact = org.finos.fo.Contact.create(
  org.finos.fo.Contact.Id.create({
    email: "maoo@finos.org", 
    twitter: "maoo", 
    phone: "+34 123456" }));

console.log(contact);