// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: contacts.proto

package org.finos.fo;

public final class Contacts {
  private Contacts() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ContactOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.finos.fo.Contact)
      com.google.protobuf.MessageOrBuilder {
  }
  /**
   * Protobuf type {@code org.finos.fo.Contact}
   */
  public  static final class Contact extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.finos.fo.Contact)
      ContactOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Contact.newBuilder() to construct.
    private Contact(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Contact() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Contact(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.finos.fo.Contacts.internal_static_org_finos_fo_Contact_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.finos.fo.Contacts.internal_static_org_finos_fo_Contact_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.finos.fo.Contacts.Contact.class, org.finos.fo.Contacts.Contact.Builder.class);
    }

    public interface IdOrBuilder extends
        // @@protoc_insertion_point(interface_extends:org.finos.fo.Contact.Id)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string email = 1;</code>
       */
      java.lang.String getEmail();
      /**
       * <code>string email = 1;</code>
       */
      com.google.protobuf.ByteString
          getEmailBytes();

      /**
       * <code>string twitter = 2;</code>
       */
      java.lang.String getTwitter();
      /**
       * <code>string twitter = 2;</code>
       */
      com.google.protobuf.ByteString
          getTwitterBytes();

      /**
       * <code>string phone = 3;</code>
       */
      java.lang.String getPhone();
      /**
       * <code>string phone = 3;</code>
       */
      com.google.protobuf.ByteString
          getPhoneBytes();
    }
    /**
     * Protobuf type {@code org.finos.fo.Contact.Id}
     */
    public  static final class Id extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:org.finos.fo.Contact.Id)
        IdOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Id.newBuilder() to construct.
      private Id(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Id() {
        email_ = "";
        twitter_ = "";
        phone_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Id(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                email_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                twitter_ = s;
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();

                phone_ = s;
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.finos.fo.Contacts.internal_static_org_finos_fo_Contact_Id_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.finos.fo.Contacts.internal_static_org_finos_fo_Contact_Id_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.finos.fo.Contacts.Contact.Id.class, org.finos.fo.Contacts.Contact.Id.Builder.class);
      }

      public static final int EMAIL_FIELD_NUMBER = 1;
      private volatile java.lang.Object email_;
      /**
       * <code>string email = 1;</code>
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        }
      }
      /**
       * <code>string email = 1;</code>
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int TWITTER_FIELD_NUMBER = 2;
      private volatile java.lang.Object twitter_;
      /**
       * <code>string twitter = 2;</code>
       */
      public java.lang.String getTwitter() {
        java.lang.Object ref = twitter_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          twitter_ = s;
          return s;
        }
      }
      /**
       * <code>string twitter = 2;</code>
       */
      public com.google.protobuf.ByteString
          getTwitterBytes() {
        java.lang.Object ref = twitter_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          twitter_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PHONE_FIELD_NUMBER = 3;
      private volatile java.lang.Object phone_;
      /**
       * <code>string phone = 3;</code>
       */
      public java.lang.String getPhone() {
        java.lang.Object ref = phone_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          phone_ = s;
          return s;
        }
      }
      /**
       * <code>string phone = 3;</code>
       */
      public com.google.protobuf.ByteString
          getPhoneBytes() {
        java.lang.Object ref = phone_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          phone_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getEmailBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, email_);
        }
        if (!getTwitterBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, twitter_);
        }
        if (!getPhoneBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, phone_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getEmailBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, email_);
        }
        if (!getTwitterBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, twitter_);
        }
        if (!getPhoneBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, phone_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof org.finos.fo.Contacts.Contact.Id)) {
          return super.equals(obj);
        }
        org.finos.fo.Contacts.Contact.Id other = (org.finos.fo.Contacts.Contact.Id) obj;

        boolean result = true;
        result = result && getEmail()
            .equals(other.getEmail());
        result = result && getTwitter()
            .equals(other.getTwitter());
        result = result && getPhone()
            .equals(other.getPhone());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + EMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getEmail().hashCode();
        hash = (37 * hash) + TWITTER_FIELD_NUMBER;
        hash = (53 * hash) + getTwitter().hashCode();
        hash = (37 * hash) + PHONE_FIELD_NUMBER;
        hash = (53 * hash) + getPhone().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.finos.fo.Contacts.Contact.Id parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.finos.fo.Contacts.Contact.Id parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.finos.fo.Contacts.Contact.Id parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.finos.fo.Contacts.Contact.Id parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.finos.fo.Contacts.Contact.Id parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.finos.fo.Contacts.Contact.Id parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.finos.fo.Contacts.Contact.Id parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.finos.fo.Contacts.Contact.Id parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.finos.fo.Contacts.Contact.Id parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static org.finos.fo.Contacts.Contact.Id parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.finos.fo.Contacts.Contact.Id parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.finos.fo.Contacts.Contact.Id parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.finos.fo.Contacts.Contact.Id prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code org.finos.fo.Contact.Id}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:org.finos.fo.Contact.Id)
          org.finos.fo.Contacts.Contact.IdOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.finos.fo.Contacts.internal_static_org_finos_fo_Contact_Id_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.finos.fo.Contacts.internal_static_org_finos_fo_Contact_Id_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.finos.fo.Contacts.Contact.Id.class, org.finos.fo.Contacts.Contact.Id.Builder.class);
        }

        // Construct using org.finos.fo.Contacts.Contact.Id.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          email_ = "";

          twitter_ = "";

          phone_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.finos.fo.Contacts.internal_static_org_finos_fo_Contact_Id_descriptor;
        }

        @java.lang.Override
        public org.finos.fo.Contacts.Contact.Id getDefaultInstanceForType() {
          return org.finos.fo.Contacts.Contact.Id.getDefaultInstance();
        }

        @java.lang.Override
        public org.finos.fo.Contacts.Contact.Id build() {
          org.finos.fo.Contacts.Contact.Id result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public org.finos.fo.Contacts.Contact.Id buildPartial() {
          org.finos.fo.Contacts.Contact.Id result = new org.finos.fo.Contacts.Contact.Id(this);
          result.email_ = email_;
          result.twitter_ = twitter_;
          result.phone_ = phone_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.finos.fo.Contacts.Contact.Id) {
            return mergeFrom((org.finos.fo.Contacts.Contact.Id)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.finos.fo.Contacts.Contact.Id other) {
          if (other == org.finos.fo.Contacts.Contact.Id.getDefaultInstance()) return this;
          if (!other.getEmail().isEmpty()) {
            email_ = other.email_;
            onChanged();
          }
          if (!other.getTwitter().isEmpty()) {
            twitter_ = other.twitter_;
            onChanged();
          }
          if (!other.getPhone().isEmpty()) {
            phone_ = other.phone_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.finos.fo.Contacts.Contact.Id parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.finos.fo.Contacts.Contact.Id) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object email_ = "";
        /**
         * <code>string email = 1;</code>
         */
        public java.lang.String getEmail() {
          java.lang.Object ref = email_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            email_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string email = 1;</code>
         */
        public com.google.protobuf.ByteString
            getEmailBytes() {
          java.lang.Object ref = email_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            email_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string email = 1;</code>
         */
        public Builder setEmail(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          email_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string email = 1;</code>
         */
        public Builder clearEmail() {
          
          email_ = getDefaultInstance().getEmail();
          onChanged();
          return this;
        }
        /**
         * <code>string email = 1;</code>
         */
        public Builder setEmailBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          email_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object twitter_ = "";
        /**
         * <code>string twitter = 2;</code>
         */
        public java.lang.String getTwitter() {
          java.lang.Object ref = twitter_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            twitter_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string twitter = 2;</code>
         */
        public com.google.protobuf.ByteString
            getTwitterBytes() {
          java.lang.Object ref = twitter_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            twitter_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string twitter = 2;</code>
         */
        public Builder setTwitter(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          twitter_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string twitter = 2;</code>
         */
        public Builder clearTwitter() {
          
          twitter_ = getDefaultInstance().getTwitter();
          onChanged();
          return this;
        }
        /**
         * <code>string twitter = 2;</code>
         */
        public Builder setTwitterBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          twitter_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object phone_ = "";
        /**
         * <code>string phone = 3;</code>
         */
        public java.lang.String getPhone() {
          java.lang.Object ref = phone_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            phone_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string phone = 3;</code>
         */
        public com.google.protobuf.ByteString
            getPhoneBytes() {
          java.lang.Object ref = phone_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            phone_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string phone = 3;</code>
         */
        public Builder setPhone(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          phone_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string phone = 3;</code>
         */
        public Builder clearPhone() {
          
          phone_ = getDefaultInstance().getPhone();
          onChanged();
          return this;
        }
        /**
         * <code>string phone = 3;</code>
         */
        public Builder setPhoneBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          phone_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:org.finos.fo.Contact.Id)
      }

      // @@protoc_insertion_point(class_scope:org.finos.fo.Contact.Id)
      private static final org.finos.fo.Contacts.Contact.Id DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.finos.fo.Contacts.Contact.Id();
      }

      public static org.finos.fo.Contacts.Contact.Id getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Id>
          PARSER = new com.google.protobuf.AbstractParser<Id>() {
        @java.lang.Override
        public Id parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Id(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Id> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Id> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public org.finos.fo.Contacts.Contact.Id getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.finos.fo.Contacts.Contact)) {
        return super.equals(obj);
      }
      org.finos.fo.Contacts.Contact other = (org.finos.fo.Contacts.Contact) obj;

      boolean result = true;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.finos.fo.Contacts.Contact parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.finos.fo.Contacts.Contact parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.finos.fo.Contacts.Contact parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.finos.fo.Contacts.Contact parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.finos.fo.Contacts.Contact parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.finos.fo.Contacts.Contact parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.finos.fo.Contacts.Contact parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.finos.fo.Contacts.Contact parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.finos.fo.Contacts.Contact parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.finos.fo.Contacts.Contact parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.finos.fo.Contacts.Contact parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.finos.fo.Contacts.Contact parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.finos.fo.Contacts.Contact prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.finos.fo.Contact}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.finos.fo.Contact)
        org.finos.fo.Contacts.ContactOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.finos.fo.Contacts.internal_static_org_finos_fo_Contact_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.finos.fo.Contacts.internal_static_org_finos_fo_Contact_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.finos.fo.Contacts.Contact.class, org.finos.fo.Contacts.Contact.Builder.class);
      }

      // Construct using org.finos.fo.Contacts.Contact.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.finos.fo.Contacts.internal_static_org_finos_fo_Contact_descriptor;
      }

      @java.lang.Override
      public org.finos.fo.Contacts.Contact getDefaultInstanceForType() {
        return org.finos.fo.Contacts.Contact.getDefaultInstance();
      }

      @java.lang.Override
      public org.finos.fo.Contacts.Contact build() {
        org.finos.fo.Contacts.Contact result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.finos.fo.Contacts.Contact buildPartial() {
        org.finos.fo.Contacts.Contact result = new org.finos.fo.Contacts.Contact(this);
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.finos.fo.Contacts.Contact) {
          return mergeFrom((org.finos.fo.Contacts.Contact)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.finos.fo.Contacts.Contact other) {
        if (other == org.finos.fo.Contacts.Contact.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.finos.fo.Contacts.Contact parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.finos.fo.Contacts.Contact) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.finos.fo.Contact)
    }

    // @@protoc_insertion_point(class_scope:org.finos.fo.Contact)
    private static final org.finos.fo.Contacts.Contact DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.finos.fo.Contacts.Contact();
    }

    public static org.finos.fo.Contacts.Contact getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Contact>
        PARSER = new com.google.protobuf.AbstractParser<Contact>() {
      @java.lang.Override
      public Contact parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Contact(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Contact> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Contact> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.finos.fo.Contacts.Contact getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ContactListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.finos.fo.ContactList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
     */
    java.util.List<org.finos.fo.Contacts.Contact> 
        getContactsList();
    /**
     * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
     */
    org.finos.fo.Contacts.Contact getContacts(int index);
    /**
     * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
     */
    int getContactsCount();
    /**
     * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
     */
    java.util.List<? extends org.finos.fo.Contacts.ContactOrBuilder> 
        getContactsOrBuilderList();
    /**
     * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
     */
    org.finos.fo.Contacts.ContactOrBuilder getContactsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.finos.fo.ContactList}
   */
  public  static final class ContactList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.finos.fo.ContactList)
      ContactListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ContactList.newBuilder() to construct.
    private ContactList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ContactList() {
      contacts_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ContactList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                contacts_ = new java.util.ArrayList<org.finos.fo.Contacts.Contact>();
                mutable_bitField0_ |= 0x00000001;
              }
              contacts_.add(
                  input.readMessage(org.finos.fo.Contacts.Contact.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          contacts_ = java.util.Collections.unmodifiableList(contacts_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.finos.fo.Contacts.internal_static_org_finos_fo_ContactList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.finos.fo.Contacts.internal_static_org_finos_fo_ContactList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.finos.fo.Contacts.ContactList.class, org.finos.fo.Contacts.ContactList.Builder.class);
    }

    public static final int CONTACTS_FIELD_NUMBER = 1;
    private java.util.List<org.finos.fo.Contacts.Contact> contacts_;
    /**
     * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
     */
    public java.util.List<org.finos.fo.Contacts.Contact> getContactsList() {
      return contacts_;
    }
    /**
     * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
     */
    public java.util.List<? extends org.finos.fo.Contacts.ContactOrBuilder> 
        getContactsOrBuilderList() {
      return contacts_;
    }
    /**
     * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
     */
    public int getContactsCount() {
      return contacts_.size();
    }
    /**
     * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
     */
    public org.finos.fo.Contacts.Contact getContacts(int index) {
      return contacts_.get(index);
    }
    /**
     * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
     */
    public org.finos.fo.Contacts.ContactOrBuilder getContactsOrBuilder(
        int index) {
      return contacts_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < contacts_.size(); i++) {
        output.writeMessage(1, contacts_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < contacts_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, contacts_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.finos.fo.Contacts.ContactList)) {
        return super.equals(obj);
      }
      org.finos.fo.Contacts.ContactList other = (org.finos.fo.Contacts.ContactList) obj;

      boolean result = true;
      result = result && getContactsList()
          .equals(other.getContactsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getContactsCount() > 0) {
        hash = (37 * hash) + CONTACTS_FIELD_NUMBER;
        hash = (53 * hash) + getContactsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.finos.fo.Contacts.ContactList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.finos.fo.Contacts.ContactList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.finos.fo.Contacts.ContactList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.finos.fo.Contacts.ContactList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.finos.fo.Contacts.ContactList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.finos.fo.Contacts.ContactList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.finos.fo.Contacts.ContactList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.finos.fo.Contacts.ContactList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.finos.fo.Contacts.ContactList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.finos.fo.Contacts.ContactList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.finos.fo.Contacts.ContactList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.finos.fo.Contacts.ContactList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.finos.fo.Contacts.ContactList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.finos.fo.ContactList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.finos.fo.ContactList)
        org.finos.fo.Contacts.ContactListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.finos.fo.Contacts.internal_static_org_finos_fo_ContactList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.finos.fo.Contacts.internal_static_org_finos_fo_ContactList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.finos.fo.Contacts.ContactList.class, org.finos.fo.Contacts.ContactList.Builder.class);
      }

      // Construct using org.finos.fo.Contacts.ContactList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getContactsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (contactsBuilder_ == null) {
          contacts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          contactsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.finos.fo.Contacts.internal_static_org_finos_fo_ContactList_descriptor;
      }

      @java.lang.Override
      public org.finos.fo.Contacts.ContactList getDefaultInstanceForType() {
        return org.finos.fo.Contacts.ContactList.getDefaultInstance();
      }

      @java.lang.Override
      public org.finos.fo.Contacts.ContactList build() {
        org.finos.fo.Contacts.ContactList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.finos.fo.Contacts.ContactList buildPartial() {
        org.finos.fo.Contacts.ContactList result = new org.finos.fo.Contacts.ContactList(this);
        int from_bitField0_ = bitField0_;
        if (contactsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            contacts_ = java.util.Collections.unmodifiableList(contacts_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.contacts_ = contacts_;
        } else {
          result.contacts_ = contactsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.finos.fo.Contacts.ContactList) {
          return mergeFrom((org.finos.fo.Contacts.ContactList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.finos.fo.Contacts.ContactList other) {
        if (other == org.finos.fo.Contacts.ContactList.getDefaultInstance()) return this;
        if (contactsBuilder_ == null) {
          if (!other.contacts_.isEmpty()) {
            if (contacts_.isEmpty()) {
              contacts_ = other.contacts_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureContactsIsMutable();
              contacts_.addAll(other.contacts_);
            }
            onChanged();
          }
        } else {
          if (!other.contacts_.isEmpty()) {
            if (contactsBuilder_.isEmpty()) {
              contactsBuilder_.dispose();
              contactsBuilder_ = null;
              contacts_ = other.contacts_;
              bitField0_ = (bitField0_ & ~0x00000001);
              contactsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getContactsFieldBuilder() : null;
            } else {
              contactsBuilder_.addAllMessages(other.contacts_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.finos.fo.Contacts.ContactList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.finos.fo.Contacts.ContactList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.finos.fo.Contacts.Contact> contacts_ =
        java.util.Collections.emptyList();
      private void ensureContactsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          contacts_ = new java.util.ArrayList<org.finos.fo.Contacts.Contact>(contacts_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.finos.fo.Contacts.Contact, org.finos.fo.Contacts.Contact.Builder, org.finos.fo.Contacts.ContactOrBuilder> contactsBuilder_;

      /**
       * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
       */
      public java.util.List<org.finos.fo.Contacts.Contact> getContactsList() {
        if (contactsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(contacts_);
        } else {
          return contactsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
       */
      public int getContactsCount() {
        if (contactsBuilder_ == null) {
          return contacts_.size();
        } else {
          return contactsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
       */
      public org.finos.fo.Contacts.Contact getContacts(int index) {
        if (contactsBuilder_ == null) {
          return contacts_.get(index);
        } else {
          return contactsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
       */
      public Builder setContacts(
          int index, org.finos.fo.Contacts.Contact value) {
        if (contactsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactsIsMutable();
          contacts_.set(index, value);
          onChanged();
        } else {
          contactsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
       */
      public Builder setContacts(
          int index, org.finos.fo.Contacts.Contact.Builder builderForValue) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.set(index, builderForValue.build());
          onChanged();
        } else {
          contactsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
       */
      public Builder addContacts(org.finos.fo.Contacts.Contact value) {
        if (contactsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactsIsMutable();
          contacts_.add(value);
          onChanged();
        } else {
          contactsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
       */
      public Builder addContacts(
          int index, org.finos.fo.Contacts.Contact value) {
        if (contactsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureContactsIsMutable();
          contacts_.add(index, value);
          onChanged();
        } else {
          contactsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
       */
      public Builder addContacts(
          org.finos.fo.Contacts.Contact.Builder builderForValue) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.add(builderForValue.build());
          onChanged();
        } else {
          contactsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
       */
      public Builder addContacts(
          int index, org.finos.fo.Contacts.Contact.Builder builderForValue) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.add(index, builderForValue.build());
          onChanged();
        } else {
          contactsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
       */
      public Builder addAllContacts(
          java.lang.Iterable<? extends org.finos.fo.Contacts.Contact> values) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, contacts_);
          onChanged();
        } else {
          contactsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
       */
      public Builder clearContacts() {
        if (contactsBuilder_ == null) {
          contacts_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          contactsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
       */
      public Builder removeContacts(int index) {
        if (contactsBuilder_ == null) {
          ensureContactsIsMutable();
          contacts_.remove(index);
          onChanged();
        } else {
          contactsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
       */
      public org.finos.fo.Contacts.Contact.Builder getContactsBuilder(
          int index) {
        return getContactsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
       */
      public org.finos.fo.Contacts.ContactOrBuilder getContactsOrBuilder(
          int index) {
        if (contactsBuilder_ == null) {
          return contacts_.get(index);  } else {
          return contactsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
       */
      public java.util.List<? extends org.finos.fo.Contacts.ContactOrBuilder> 
           getContactsOrBuilderList() {
        if (contactsBuilder_ != null) {
          return contactsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(contacts_);
        }
      }
      /**
       * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
       */
      public org.finos.fo.Contacts.Contact.Builder addContactsBuilder() {
        return getContactsFieldBuilder().addBuilder(
            org.finos.fo.Contacts.Contact.getDefaultInstance());
      }
      /**
       * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
       */
      public org.finos.fo.Contacts.Contact.Builder addContactsBuilder(
          int index) {
        return getContactsFieldBuilder().addBuilder(
            index, org.finos.fo.Contacts.Contact.getDefaultInstance());
      }
      /**
       * <code>repeated .org.finos.fo.Contact contacts = 1;</code>
       */
      public java.util.List<org.finos.fo.Contacts.Contact.Builder> 
           getContactsBuilderList() {
        return getContactsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.finos.fo.Contacts.Contact, org.finos.fo.Contacts.Contact.Builder, org.finos.fo.Contacts.ContactOrBuilder> 
          getContactsFieldBuilder() {
        if (contactsBuilder_ == null) {
          contactsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.finos.fo.Contacts.Contact, org.finos.fo.Contacts.Contact.Builder, org.finos.fo.Contacts.ContactOrBuilder>(
                  contacts_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          contacts_ = null;
        }
        return contactsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.finos.fo.ContactList)
    }

    // @@protoc_insertion_point(class_scope:org.finos.fo.ContactList)
    private static final org.finos.fo.Contacts.ContactList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.finos.fo.Contacts.ContactList();
    }

    public static org.finos.fo.Contacts.ContactList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ContactList>
        PARSER = new com.google.protobuf.AbstractParser<ContactList>() {
      @java.lang.Override
      public ContactList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ContactList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ContactList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ContactList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.finos.fo.Contacts.ContactList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_finos_fo_Contact_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_finos_fo_Contact_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_finos_fo_Contact_Id_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_finos_fo_Contact_Id_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_finos_fo_ContactList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_finos_fo_ContactList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016contacts.proto\022\014org.finos.fo\">\n\007Contac" +
      "t\0323\n\002Id\022\r\n\005email\030\001 \001(\t\022\017\n\007twitter\030\002 \001(\t\022" +
      "\r\n\005phone\030\003 \001(\t\"6\n\013ContactList\022\'\n\010contact" +
      "s\030\001 \003(\0132\025.org.finos.fo.ContactB\016\n\014org.fi" +
      "nos.fob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_finos_fo_Contact_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_finos_fo_Contact_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_finos_fo_Contact_descriptor,
        new java.lang.String[] { });
    internal_static_org_finos_fo_Contact_Id_descriptor =
      internal_static_org_finos_fo_Contact_descriptor.getNestedTypes().get(0);
    internal_static_org_finos_fo_Contact_Id_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_finos_fo_Contact_Id_descriptor,
        new java.lang.String[] { "Email", "Twitter", "Phone", });
    internal_static_org_finos_fo_ContactList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_finos_fo_ContactList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_finos_fo_ContactList_descriptor,
        new java.lang.String[] { "Contacts", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
