// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: country.proto

package org.finos.fo;

public final class CountryOuterClass {
  private CountryOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CountryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.finos.fo.Country)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code org.finos.fo.Country}
   */
  public  static final class Country extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.finos.fo.Country)
      CountryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Country.newBuilder() to construct.
    private Country(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Country() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Country(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.finos.fo.CountryOuterClass.internal_static_org_finos_fo_Country_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.finos.fo.CountryOuterClass.internal_static_org_finos_fo_Country_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.finos.fo.CountryOuterClass.Country.class, org.finos.fo.CountryOuterClass.Country.Builder.class);
    }

    public interface IdOrBuilder extends
        // @@protoc_insertion_point(interface_extends:org.finos.fo.Country.Id)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string ISOALPHA2 = 1;</code>
       */
      java.lang.String getISOALPHA2();
      /**
       * <code>string ISOALPHA2 = 1;</code>
       */
      com.google.protobuf.ByteString
          getISOALPHA2Bytes();

      /**
       * <code>string ISOALPHA3 = 2;</code>
       */
      java.lang.String getISOALPHA3();
      /**
       * <code>string ISOALPHA3 = 2;</code>
       */
      com.google.protobuf.ByteString
          getISOALPHA3Bytes();
    }
    /**
     * Protobuf type {@code org.finos.fo.Country.Id}
     */
    public  static final class Id extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:org.finos.fo.Country.Id)
        IdOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Id.newBuilder() to construct.
      private Id(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Id() {
        iSOALPHA2_ = "";
        iSOALPHA3_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Id(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                iSOALPHA2_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                iSOALPHA3_ = s;
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.finos.fo.CountryOuterClass.internal_static_org_finos_fo_Country_Id_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.finos.fo.CountryOuterClass.internal_static_org_finos_fo_Country_Id_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.finos.fo.CountryOuterClass.Country.Id.class, org.finos.fo.CountryOuterClass.Country.Id.Builder.class);
      }

      public static final int ISOALPHA2_FIELD_NUMBER = 1;
      private volatile java.lang.Object iSOALPHA2_;
      /**
       * <code>string ISOALPHA2 = 1;</code>
       */
      public java.lang.String getISOALPHA2() {
        java.lang.Object ref = iSOALPHA2_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          iSOALPHA2_ = s;
          return s;
        }
      }
      /**
       * <code>string ISOALPHA2 = 1;</code>
       */
      public com.google.protobuf.ByteString
          getISOALPHA2Bytes() {
        java.lang.Object ref = iSOALPHA2_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iSOALPHA2_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ISOALPHA3_FIELD_NUMBER = 2;
      private volatile java.lang.Object iSOALPHA3_;
      /**
       * <code>string ISOALPHA3 = 2;</code>
       */
      public java.lang.String getISOALPHA3() {
        java.lang.Object ref = iSOALPHA3_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          iSOALPHA3_ = s;
          return s;
        }
      }
      /**
       * <code>string ISOALPHA3 = 2;</code>
       */
      public com.google.protobuf.ByteString
          getISOALPHA3Bytes() {
        java.lang.Object ref = iSOALPHA3_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iSOALPHA3_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getISOALPHA2Bytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, iSOALPHA2_);
        }
        if (!getISOALPHA3Bytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, iSOALPHA3_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getISOALPHA2Bytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, iSOALPHA2_);
        }
        if (!getISOALPHA3Bytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, iSOALPHA3_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof org.finos.fo.CountryOuterClass.Country.Id)) {
          return super.equals(obj);
        }
        org.finos.fo.CountryOuterClass.Country.Id other = (org.finos.fo.CountryOuterClass.Country.Id) obj;

        boolean result = true;
        result = result && getISOALPHA2()
            .equals(other.getISOALPHA2());
        result = result && getISOALPHA3()
            .equals(other.getISOALPHA3());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ISOALPHA2_FIELD_NUMBER;
        hash = (53 * hash) + getISOALPHA2().hashCode();
        hash = (37 * hash) + ISOALPHA3_FIELD_NUMBER;
        hash = (53 * hash) + getISOALPHA3().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.finos.fo.CountryOuterClass.Country.Id parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.finos.fo.CountryOuterClass.Country.Id parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.finos.fo.CountryOuterClass.Country.Id parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.finos.fo.CountryOuterClass.Country.Id parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.finos.fo.CountryOuterClass.Country.Id parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.finos.fo.CountryOuterClass.Country.Id parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.finos.fo.CountryOuterClass.Country.Id parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.finos.fo.CountryOuterClass.Country.Id parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.finos.fo.CountryOuterClass.Country.Id parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static org.finos.fo.CountryOuterClass.Country.Id parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.finos.fo.CountryOuterClass.Country.Id parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.finos.fo.CountryOuterClass.Country.Id parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.finos.fo.CountryOuterClass.Country.Id prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code org.finos.fo.Country.Id}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:org.finos.fo.Country.Id)
          org.finos.fo.CountryOuterClass.Country.IdOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.finos.fo.CountryOuterClass.internal_static_org_finos_fo_Country_Id_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.finos.fo.CountryOuterClass.internal_static_org_finos_fo_Country_Id_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.finos.fo.CountryOuterClass.Country.Id.class, org.finos.fo.CountryOuterClass.Country.Id.Builder.class);
        }

        // Construct using org.finos.fo.CountryOuterClass.Country.Id.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          iSOALPHA2_ = "";

          iSOALPHA3_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.finos.fo.CountryOuterClass.internal_static_org_finos_fo_Country_Id_descriptor;
        }

        @java.lang.Override
        public org.finos.fo.CountryOuterClass.Country.Id getDefaultInstanceForType() {
          return org.finos.fo.CountryOuterClass.Country.Id.getDefaultInstance();
        }

        @java.lang.Override
        public org.finos.fo.CountryOuterClass.Country.Id build() {
          org.finos.fo.CountryOuterClass.Country.Id result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public org.finos.fo.CountryOuterClass.Country.Id buildPartial() {
          org.finos.fo.CountryOuterClass.Country.Id result = new org.finos.fo.CountryOuterClass.Country.Id(this);
          result.iSOALPHA2_ = iSOALPHA2_;
          result.iSOALPHA3_ = iSOALPHA3_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.finos.fo.CountryOuterClass.Country.Id) {
            return mergeFrom((org.finos.fo.CountryOuterClass.Country.Id)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.finos.fo.CountryOuterClass.Country.Id other) {
          if (other == org.finos.fo.CountryOuterClass.Country.Id.getDefaultInstance()) return this;
          if (!other.getISOALPHA2().isEmpty()) {
            iSOALPHA2_ = other.iSOALPHA2_;
            onChanged();
          }
          if (!other.getISOALPHA3().isEmpty()) {
            iSOALPHA3_ = other.iSOALPHA3_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.finos.fo.CountryOuterClass.Country.Id parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.finos.fo.CountryOuterClass.Country.Id) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object iSOALPHA2_ = "";
        /**
         * <code>string ISOALPHA2 = 1;</code>
         */
        public java.lang.String getISOALPHA2() {
          java.lang.Object ref = iSOALPHA2_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            iSOALPHA2_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string ISOALPHA2 = 1;</code>
         */
        public com.google.protobuf.ByteString
            getISOALPHA2Bytes() {
          java.lang.Object ref = iSOALPHA2_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            iSOALPHA2_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string ISOALPHA2 = 1;</code>
         */
        public Builder setISOALPHA2(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          iSOALPHA2_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string ISOALPHA2 = 1;</code>
         */
        public Builder clearISOALPHA2() {
          
          iSOALPHA2_ = getDefaultInstance().getISOALPHA2();
          onChanged();
          return this;
        }
        /**
         * <code>string ISOALPHA2 = 1;</code>
         */
        public Builder setISOALPHA2Bytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          iSOALPHA2_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object iSOALPHA3_ = "";
        /**
         * <code>string ISOALPHA3 = 2;</code>
         */
        public java.lang.String getISOALPHA3() {
          java.lang.Object ref = iSOALPHA3_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            iSOALPHA3_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string ISOALPHA3 = 2;</code>
         */
        public com.google.protobuf.ByteString
            getISOALPHA3Bytes() {
          java.lang.Object ref = iSOALPHA3_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            iSOALPHA3_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string ISOALPHA3 = 2;</code>
         */
        public Builder setISOALPHA3(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          iSOALPHA3_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string ISOALPHA3 = 2;</code>
         */
        public Builder clearISOALPHA3() {
          
          iSOALPHA3_ = getDefaultInstance().getISOALPHA3();
          onChanged();
          return this;
        }
        /**
         * <code>string ISOALPHA3 = 2;</code>
         */
        public Builder setISOALPHA3Bytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          iSOALPHA3_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:org.finos.fo.Country.Id)
      }

      // @@protoc_insertion_point(class_scope:org.finos.fo.Country.Id)
      private static final org.finos.fo.CountryOuterClass.Country.Id DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.finos.fo.CountryOuterClass.Country.Id();
      }

      public static org.finos.fo.CountryOuterClass.Country.Id getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Id>
          PARSER = new com.google.protobuf.AbstractParser<Id>() {
        @java.lang.Override
        public Id parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Id(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Id> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Id> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public org.finos.fo.CountryOuterClass.Country.Id getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.finos.fo.CountryOuterClass.Country)) {
        return super.equals(obj);
      }
      org.finos.fo.CountryOuterClass.Country other = (org.finos.fo.CountryOuterClass.Country) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.finos.fo.CountryOuterClass.Country parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.finos.fo.CountryOuterClass.Country parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.finos.fo.CountryOuterClass.Country parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.finos.fo.CountryOuterClass.Country parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.finos.fo.CountryOuterClass.Country parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.finos.fo.CountryOuterClass.Country parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.finos.fo.CountryOuterClass.Country parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.finos.fo.CountryOuterClass.Country parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.finos.fo.CountryOuterClass.Country parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.finos.fo.CountryOuterClass.Country parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.finos.fo.CountryOuterClass.Country parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.finos.fo.CountryOuterClass.Country parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.finos.fo.CountryOuterClass.Country prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.finos.fo.Country}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.finos.fo.Country)
        org.finos.fo.CountryOuterClass.CountryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.finos.fo.CountryOuterClass.internal_static_org_finos_fo_Country_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.finos.fo.CountryOuterClass.internal_static_org_finos_fo_Country_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.finos.fo.CountryOuterClass.Country.class, org.finos.fo.CountryOuterClass.Country.Builder.class);
      }

      // Construct using org.finos.fo.CountryOuterClass.Country.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.finos.fo.CountryOuterClass.internal_static_org_finos_fo_Country_descriptor;
      }

      @java.lang.Override
      public org.finos.fo.CountryOuterClass.Country getDefaultInstanceForType() {
        return org.finos.fo.CountryOuterClass.Country.getDefaultInstance();
      }

      @java.lang.Override
      public org.finos.fo.CountryOuterClass.Country build() {
        org.finos.fo.CountryOuterClass.Country result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.finos.fo.CountryOuterClass.Country buildPartial() {
        org.finos.fo.CountryOuterClass.Country result = new org.finos.fo.CountryOuterClass.Country(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.finos.fo.CountryOuterClass.Country) {
          return mergeFrom((org.finos.fo.CountryOuterClass.Country)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.finos.fo.CountryOuterClass.Country other) {
        if (other == org.finos.fo.CountryOuterClass.Country.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.finos.fo.CountryOuterClass.Country parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.finos.fo.CountryOuterClass.Country) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.finos.fo.Country)
    }

    // @@protoc_insertion_point(class_scope:org.finos.fo.Country)
    private static final org.finos.fo.CountryOuterClass.Country DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.finos.fo.CountryOuterClass.Country();
    }

    public static org.finos.fo.CountryOuterClass.Country getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Country>
        PARSER = new com.google.protobuf.AbstractParser<Country>() {
      @java.lang.Override
      public Country parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Country(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Country> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Country> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.finos.fo.CountryOuterClass.Country getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_finos_fo_Country_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_finos_fo_Country_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_finos_fo_Country_Id_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_finos_fo_Country_Id_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\rcountry.proto\022\014org.finos.fo\"C\n\007Country" +
      "\022\014\n\004name\030\001 \001(\t\032*\n\002Id\022\021\n\tISOALPHA2\030\001 \001(\t\022" +
      "\021\n\tISOALPHA3\030\002 \001(\tB\016\n\014org.finos.fob\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_finos_fo_Country_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_finos_fo_Country_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_finos_fo_Country_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_org_finos_fo_Country_Id_descriptor =
      internal_static_org_finos_fo_Country_descriptor.getNestedTypes().get(0);
    internal_static_org_finos_fo_Country_Id_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_finos_fo_Country_Id_descriptor,
        new java.lang.String[] { "ISOALPHA2", "ISOALPHA3", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
