// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: instruments.proto

package org.finos.fo;

public final class Instruments {
  private Instruments() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface InstrumentOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.finos.fo.Instrument)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();
  }
  /**
   * Protobuf type {@code org.finos.fo.Instrument}
   */
  public  static final class Instrument extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.finos.fo.Instrument)
      InstrumentOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Instrument.newBuilder() to construct.
    private Instrument(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Instrument() {
      name_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Instrument(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.finos.fo.Instruments.internal_static_org_finos_fo_Instrument_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.finos.fo.Instruments.internal_static_org_finos_fo_Instrument_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.finos.fo.Instruments.Instrument.class, org.finos.fo.Instruments.Instrument.Builder.class);
    }

    public interface IdOrBuilder extends
        // @@protoc_insertion_point(interface_extends:org.finos.fo.Instrument.Id)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string ticker = 1;</code>
       */
      java.lang.String getTicker();
      /**
       * <code>string ticker = 1;</code>
       */
      com.google.protobuf.ByteString
          getTickerBytes();

      /**
       * <code>string ISIN = 2;</code>
       */
      java.lang.String getISIN();
      /**
       * <code>string ISIN = 2;</code>
       */
      com.google.protobuf.ByteString
          getISINBytes();

      /**
       * <code>string CUSIP = 3;</code>
       */
      java.lang.String getCUSIP();
      /**
       * <code>string CUSIP = 3;</code>
       */
      com.google.protobuf.ByteString
          getCUSIPBytes();

      /**
       * <code>string SEDOL = 4;</code>
       */
      java.lang.String getSEDOL();
      /**
       * <code>string SEDOL = 4;</code>
       */
      com.google.protobuf.ByteString
          getSEDOLBytes();

      /**
       * <code>string RIC = 5;</code>
       */
      java.lang.String getRIC();
      /**
       * <code>string RIC = 5;</code>
       */
      com.google.protobuf.ByteString
          getRICBytes();

      /**
       * <code>string BBG = 6;</code>
       */
      java.lang.String getBBG();
      /**
       * <code>string BBG = 6;</code>
       */
      com.google.protobuf.ByteString
          getBBGBytes();

      /**
       * <code>string PERMID = 7;</code>
       */
      java.lang.String getPERMID();
      /**
       * <code>string PERMID = 7;</code>
       */
      com.google.protobuf.ByteString
          getPERMIDBytes();

      /**
       * <code>string FIGI = 8;</code>
       */
      java.lang.String getFIGI();
      /**
       * <code>string FIGI = 8;</code>
       */
      com.google.protobuf.ByteString
          getFIGIBytes();
    }
    /**
     * Protobuf type {@code org.finos.fo.Instrument.Id}
     */
    public  static final class Id extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:org.finos.fo.Instrument.Id)
        IdOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Id.newBuilder() to construct.
      private Id(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Id() {
        ticker_ = "";
        iSIN_ = "";
        cUSIP_ = "";
        sEDOL_ = "";
        rIC_ = "";
        bBG_ = "";
        pERMID_ = "";
        fIGI_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Id(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                ticker_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                iSIN_ = s;
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();

                cUSIP_ = s;
                break;
              }
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();

                sEDOL_ = s;
                break;
              }
              case 42: {
                java.lang.String s = input.readStringRequireUtf8();

                rIC_ = s;
                break;
              }
              case 50: {
                java.lang.String s = input.readStringRequireUtf8();

                bBG_ = s;
                break;
              }
              case 58: {
                java.lang.String s = input.readStringRequireUtf8();

                pERMID_ = s;
                break;
              }
              case 66: {
                java.lang.String s = input.readStringRequireUtf8();

                fIGI_ = s;
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.finos.fo.Instruments.internal_static_org_finos_fo_Instrument_Id_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.finos.fo.Instruments.internal_static_org_finos_fo_Instrument_Id_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.finos.fo.Instruments.Instrument.Id.class, org.finos.fo.Instruments.Instrument.Id.Builder.class);
      }

      public static final int TICKER_FIELD_NUMBER = 1;
      private volatile java.lang.Object ticker_;
      /**
       * <code>string ticker = 1;</code>
       */
      public java.lang.String getTicker() {
        java.lang.Object ref = ticker_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          ticker_ = s;
          return s;
        }
      }
      /**
       * <code>string ticker = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTickerBytes() {
        java.lang.Object ref = ticker_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          ticker_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ISIN_FIELD_NUMBER = 2;
      private volatile java.lang.Object iSIN_;
      /**
       * <code>string ISIN = 2;</code>
       */
      public java.lang.String getISIN() {
        java.lang.Object ref = iSIN_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          iSIN_ = s;
          return s;
        }
      }
      /**
       * <code>string ISIN = 2;</code>
       */
      public com.google.protobuf.ByteString
          getISINBytes() {
        java.lang.Object ref = iSIN_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          iSIN_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int CUSIP_FIELD_NUMBER = 3;
      private volatile java.lang.Object cUSIP_;
      /**
       * <code>string CUSIP = 3;</code>
       */
      public java.lang.String getCUSIP() {
        java.lang.Object ref = cUSIP_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cUSIP_ = s;
          return s;
        }
      }
      /**
       * <code>string CUSIP = 3;</code>
       */
      public com.google.protobuf.ByteString
          getCUSIPBytes() {
        java.lang.Object ref = cUSIP_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cUSIP_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int SEDOL_FIELD_NUMBER = 4;
      private volatile java.lang.Object sEDOL_;
      /**
       * <code>string SEDOL = 4;</code>
       */
      public java.lang.String getSEDOL() {
        java.lang.Object ref = sEDOL_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          sEDOL_ = s;
          return s;
        }
      }
      /**
       * <code>string SEDOL = 4;</code>
       */
      public com.google.protobuf.ByteString
          getSEDOLBytes() {
        java.lang.Object ref = sEDOL_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sEDOL_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int RIC_FIELD_NUMBER = 5;
      private volatile java.lang.Object rIC_;
      /**
       * <code>string RIC = 5;</code>
       */
      public java.lang.String getRIC() {
        java.lang.Object ref = rIC_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          rIC_ = s;
          return s;
        }
      }
      /**
       * <code>string RIC = 5;</code>
       */
      public com.google.protobuf.ByteString
          getRICBytes() {
        java.lang.Object ref = rIC_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rIC_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int BBG_FIELD_NUMBER = 6;
      private volatile java.lang.Object bBG_;
      /**
       * <code>string BBG = 6;</code>
       */
      public java.lang.String getBBG() {
        java.lang.Object ref = bBG_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          bBG_ = s;
          return s;
        }
      }
      /**
       * <code>string BBG = 6;</code>
       */
      public com.google.protobuf.ByteString
          getBBGBytes() {
        java.lang.Object ref = bBG_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          bBG_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int PERMID_FIELD_NUMBER = 7;
      private volatile java.lang.Object pERMID_;
      /**
       * <code>string PERMID = 7;</code>
       */
      public java.lang.String getPERMID() {
        java.lang.Object ref = pERMID_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          pERMID_ = s;
          return s;
        }
      }
      /**
       * <code>string PERMID = 7;</code>
       */
      public com.google.protobuf.ByteString
          getPERMIDBytes() {
        java.lang.Object ref = pERMID_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          pERMID_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int FIGI_FIELD_NUMBER = 8;
      private volatile java.lang.Object fIGI_;
      /**
       * <code>string FIGI = 8;</code>
       */
      public java.lang.String getFIGI() {
        java.lang.Object ref = fIGI_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          fIGI_ = s;
          return s;
        }
      }
      /**
       * <code>string FIGI = 8;</code>
       */
      public com.google.protobuf.ByteString
          getFIGIBytes() {
        java.lang.Object ref = fIGI_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fIGI_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getTickerBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ticker_);
        }
        if (!getISINBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, iSIN_);
        }
        if (!getCUSIPBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, cUSIP_);
        }
        if (!getSEDOLBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, sEDOL_);
        }
        if (!getRICBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 5, rIC_);
        }
        if (!getBBGBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 6, bBG_);
        }
        if (!getPERMIDBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 7, pERMID_);
        }
        if (!getFIGIBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 8, fIGI_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getTickerBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, ticker_);
        }
        if (!getISINBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, iSIN_);
        }
        if (!getCUSIPBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, cUSIP_);
        }
        if (!getSEDOLBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, sEDOL_);
        }
        if (!getRICBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, rIC_);
        }
        if (!getBBGBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, bBG_);
        }
        if (!getPERMIDBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, pERMID_);
        }
        if (!getFIGIBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(8, fIGI_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof org.finos.fo.Instruments.Instrument.Id)) {
          return super.equals(obj);
        }
        org.finos.fo.Instruments.Instrument.Id other = (org.finos.fo.Instruments.Instrument.Id) obj;

        boolean result = true;
        result = result && getTicker()
            .equals(other.getTicker());
        result = result && getISIN()
            .equals(other.getISIN());
        result = result && getCUSIP()
            .equals(other.getCUSIP());
        result = result && getSEDOL()
            .equals(other.getSEDOL());
        result = result && getRIC()
            .equals(other.getRIC());
        result = result && getBBG()
            .equals(other.getBBG());
        result = result && getPERMID()
            .equals(other.getPERMID());
        result = result && getFIGI()
            .equals(other.getFIGI());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + TICKER_FIELD_NUMBER;
        hash = (53 * hash) + getTicker().hashCode();
        hash = (37 * hash) + ISIN_FIELD_NUMBER;
        hash = (53 * hash) + getISIN().hashCode();
        hash = (37 * hash) + CUSIP_FIELD_NUMBER;
        hash = (53 * hash) + getCUSIP().hashCode();
        hash = (37 * hash) + SEDOL_FIELD_NUMBER;
        hash = (53 * hash) + getSEDOL().hashCode();
        hash = (37 * hash) + RIC_FIELD_NUMBER;
        hash = (53 * hash) + getRIC().hashCode();
        hash = (37 * hash) + BBG_FIELD_NUMBER;
        hash = (53 * hash) + getBBG().hashCode();
        hash = (37 * hash) + PERMID_FIELD_NUMBER;
        hash = (53 * hash) + getPERMID().hashCode();
        hash = (37 * hash) + FIGI_FIELD_NUMBER;
        hash = (53 * hash) + getFIGI().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.finos.fo.Instruments.Instrument.Id parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.finos.fo.Instruments.Instrument.Id parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.finos.fo.Instruments.Instrument.Id parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.finos.fo.Instruments.Instrument.Id parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.finos.fo.Instruments.Instrument.Id parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.finos.fo.Instruments.Instrument.Id parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.finos.fo.Instruments.Instrument.Id parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.finos.fo.Instruments.Instrument.Id parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.finos.fo.Instruments.Instrument.Id parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static org.finos.fo.Instruments.Instrument.Id parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.finos.fo.Instruments.Instrument.Id parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.finos.fo.Instruments.Instrument.Id parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.finos.fo.Instruments.Instrument.Id prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code org.finos.fo.Instrument.Id}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:org.finos.fo.Instrument.Id)
          org.finos.fo.Instruments.Instrument.IdOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.finos.fo.Instruments.internal_static_org_finos_fo_Instrument_Id_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.finos.fo.Instruments.internal_static_org_finos_fo_Instrument_Id_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.finos.fo.Instruments.Instrument.Id.class, org.finos.fo.Instruments.Instrument.Id.Builder.class);
        }

        // Construct using org.finos.fo.Instruments.Instrument.Id.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          ticker_ = "";

          iSIN_ = "";

          cUSIP_ = "";

          sEDOL_ = "";

          rIC_ = "";

          bBG_ = "";

          pERMID_ = "";

          fIGI_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.finos.fo.Instruments.internal_static_org_finos_fo_Instrument_Id_descriptor;
        }

        @java.lang.Override
        public org.finos.fo.Instruments.Instrument.Id getDefaultInstanceForType() {
          return org.finos.fo.Instruments.Instrument.Id.getDefaultInstance();
        }

        @java.lang.Override
        public org.finos.fo.Instruments.Instrument.Id build() {
          org.finos.fo.Instruments.Instrument.Id result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public org.finos.fo.Instruments.Instrument.Id buildPartial() {
          org.finos.fo.Instruments.Instrument.Id result = new org.finos.fo.Instruments.Instrument.Id(this);
          result.ticker_ = ticker_;
          result.iSIN_ = iSIN_;
          result.cUSIP_ = cUSIP_;
          result.sEDOL_ = sEDOL_;
          result.rIC_ = rIC_;
          result.bBG_ = bBG_;
          result.pERMID_ = pERMID_;
          result.fIGI_ = fIGI_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.finos.fo.Instruments.Instrument.Id) {
            return mergeFrom((org.finos.fo.Instruments.Instrument.Id)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.finos.fo.Instruments.Instrument.Id other) {
          if (other == org.finos.fo.Instruments.Instrument.Id.getDefaultInstance()) return this;
          if (!other.getTicker().isEmpty()) {
            ticker_ = other.ticker_;
            onChanged();
          }
          if (!other.getISIN().isEmpty()) {
            iSIN_ = other.iSIN_;
            onChanged();
          }
          if (!other.getCUSIP().isEmpty()) {
            cUSIP_ = other.cUSIP_;
            onChanged();
          }
          if (!other.getSEDOL().isEmpty()) {
            sEDOL_ = other.sEDOL_;
            onChanged();
          }
          if (!other.getRIC().isEmpty()) {
            rIC_ = other.rIC_;
            onChanged();
          }
          if (!other.getBBG().isEmpty()) {
            bBG_ = other.bBG_;
            onChanged();
          }
          if (!other.getPERMID().isEmpty()) {
            pERMID_ = other.pERMID_;
            onChanged();
          }
          if (!other.getFIGI().isEmpty()) {
            fIGI_ = other.fIGI_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.finos.fo.Instruments.Instrument.Id parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.finos.fo.Instruments.Instrument.Id) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object ticker_ = "";
        /**
         * <code>string ticker = 1;</code>
         */
        public java.lang.String getTicker() {
          java.lang.Object ref = ticker_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            ticker_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string ticker = 1;</code>
         */
        public com.google.protobuf.ByteString
            getTickerBytes() {
          java.lang.Object ref = ticker_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            ticker_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string ticker = 1;</code>
         */
        public Builder setTicker(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          ticker_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string ticker = 1;</code>
         */
        public Builder clearTicker() {
          
          ticker_ = getDefaultInstance().getTicker();
          onChanged();
          return this;
        }
        /**
         * <code>string ticker = 1;</code>
         */
        public Builder setTickerBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          ticker_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object iSIN_ = "";
        /**
         * <code>string ISIN = 2;</code>
         */
        public java.lang.String getISIN() {
          java.lang.Object ref = iSIN_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            iSIN_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string ISIN = 2;</code>
         */
        public com.google.protobuf.ByteString
            getISINBytes() {
          java.lang.Object ref = iSIN_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            iSIN_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string ISIN = 2;</code>
         */
        public Builder setISIN(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          iSIN_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string ISIN = 2;</code>
         */
        public Builder clearISIN() {
          
          iSIN_ = getDefaultInstance().getISIN();
          onChanged();
          return this;
        }
        /**
         * <code>string ISIN = 2;</code>
         */
        public Builder setISINBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          iSIN_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object cUSIP_ = "";
        /**
         * <code>string CUSIP = 3;</code>
         */
        public java.lang.String getCUSIP() {
          java.lang.Object ref = cUSIP_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            cUSIP_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string CUSIP = 3;</code>
         */
        public com.google.protobuf.ByteString
            getCUSIPBytes() {
          java.lang.Object ref = cUSIP_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            cUSIP_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string CUSIP = 3;</code>
         */
        public Builder setCUSIP(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          cUSIP_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string CUSIP = 3;</code>
         */
        public Builder clearCUSIP() {
          
          cUSIP_ = getDefaultInstance().getCUSIP();
          onChanged();
          return this;
        }
        /**
         * <code>string CUSIP = 3;</code>
         */
        public Builder setCUSIPBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          cUSIP_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object sEDOL_ = "";
        /**
         * <code>string SEDOL = 4;</code>
         */
        public java.lang.String getSEDOL() {
          java.lang.Object ref = sEDOL_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            sEDOL_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string SEDOL = 4;</code>
         */
        public com.google.protobuf.ByteString
            getSEDOLBytes() {
          java.lang.Object ref = sEDOL_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            sEDOL_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string SEDOL = 4;</code>
         */
        public Builder setSEDOL(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          sEDOL_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string SEDOL = 4;</code>
         */
        public Builder clearSEDOL() {
          
          sEDOL_ = getDefaultInstance().getSEDOL();
          onChanged();
          return this;
        }
        /**
         * <code>string SEDOL = 4;</code>
         */
        public Builder setSEDOLBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          sEDOL_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object rIC_ = "";
        /**
         * <code>string RIC = 5;</code>
         */
        public java.lang.String getRIC() {
          java.lang.Object ref = rIC_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            rIC_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string RIC = 5;</code>
         */
        public com.google.protobuf.ByteString
            getRICBytes() {
          java.lang.Object ref = rIC_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            rIC_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string RIC = 5;</code>
         */
        public Builder setRIC(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          rIC_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string RIC = 5;</code>
         */
        public Builder clearRIC() {
          
          rIC_ = getDefaultInstance().getRIC();
          onChanged();
          return this;
        }
        /**
         * <code>string RIC = 5;</code>
         */
        public Builder setRICBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          rIC_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object bBG_ = "";
        /**
         * <code>string BBG = 6;</code>
         */
        public java.lang.String getBBG() {
          java.lang.Object ref = bBG_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            bBG_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string BBG = 6;</code>
         */
        public com.google.protobuf.ByteString
            getBBGBytes() {
          java.lang.Object ref = bBG_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            bBG_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string BBG = 6;</code>
         */
        public Builder setBBG(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          bBG_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string BBG = 6;</code>
         */
        public Builder clearBBG() {
          
          bBG_ = getDefaultInstance().getBBG();
          onChanged();
          return this;
        }
        /**
         * <code>string BBG = 6;</code>
         */
        public Builder setBBGBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          bBG_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object pERMID_ = "";
        /**
         * <code>string PERMID = 7;</code>
         */
        public java.lang.String getPERMID() {
          java.lang.Object ref = pERMID_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            pERMID_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string PERMID = 7;</code>
         */
        public com.google.protobuf.ByteString
            getPERMIDBytes() {
          java.lang.Object ref = pERMID_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            pERMID_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string PERMID = 7;</code>
         */
        public Builder setPERMID(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          pERMID_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string PERMID = 7;</code>
         */
        public Builder clearPERMID() {
          
          pERMID_ = getDefaultInstance().getPERMID();
          onChanged();
          return this;
        }
        /**
         * <code>string PERMID = 7;</code>
         */
        public Builder setPERMIDBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          pERMID_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object fIGI_ = "";
        /**
         * <code>string FIGI = 8;</code>
         */
        public java.lang.String getFIGI() {
          java.lang.Object ref = fIGI_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            fIGI_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string FIGI = 8;</code>
         */
        public com.google.protobuf.ByteString
            getFIGIBytes() {
          java.lang.Object ref = fIGI_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            fIGI_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string FIGI = 8;</code>
         */
        public Builder setFIGI(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          fIGI_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string FIGI = 8;</code>
         */
        public Builder clearFIGI() {
          
          fIGI_ = getDefaultInstance().getFIGI();
          onChanged();
          return this;
        }
        /**
         * <code>string FIGI = 8;</code>
         */
        public Builder setFIGIBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          fIGI_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:org.finos.fo.Instrument.Id)
      }

      // @@protoc_insertion_point(class_scope:org.finos.fo.Instrument.Id)
      private static final org.finos.fo.Instruments.Instrument.Id DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.finos.fo.Instruments.Instrument.Id();
      }

      public static org.finos.fo.Instruments.Instrument.Id getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Id>
          PARSER = new com.google.protobuf.AbstractParser<Id>() {
        @java.lang.Override
        public Id parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Id(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Id> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Id> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public org.finos.fo.Instruments.Instrument.Id getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.finos.fo.Instruments.Instrument)) {
        return super.equals(obj);
      }
      org.finos.fo.Instruments.Instrument other = (org.finos.fo.Instruments.Instrument) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.finos.fo.Instruments.Instrument parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.finos.fo.Instruments.Instrument parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.finos.fo.Instruments.Instrument parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.finos.fo.Instruments.Instrument parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.finos.fo.Instruments.Instrument parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.finos.fo.Instruments.Instrument parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.finos.fo.Instruments.Instrument parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.finos.fo.Instruments.Instrument parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.finos.fo.Instruments.Instrument parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.finos.fo.Instruments.Instrument parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.finos.fo.Instruments.Instrument parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.finos.fo.Instruments.Instrument parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.finos.fo.Instruments.Instrument prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.finos.fo.Instrument}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.finos.fo.Instrument)
        org.finos.fo.Instruments.InstrumentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.finos.fo.Instruments.internal_static_org_finos_fo_Instrument_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.finos.fo.Instruments.internal_static_org_finos_fo_Instrument_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.finos.fo.Instruments.Instrument.class, org.finos.fo.Instruments.Instrument.Builder.class);
      }

      // Construct using org.finos.fo.Instruments.Instrument.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.finos.fo.Instruments.internal_static_org_finos_fo_Instrument_descriptor;
      }

      @java.lang.Override
      public org.finos.fo.Instruments.Instrument getDefaultInstanceForType() {
        return org.finos.fo.Instruments.Instrument.getDefaultInstance();
      }

      @java.lang.Override
      public org.finos.fo.Instruments.Instrument build() {
        org.finos.fo.Instruments.Instrument result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.finos.fo.Instruments.Instrument buildPartial() {
        org.finos.fo.Instruments.Instrument result = new org.finos.fo.Instruments.Instrument(this);
        result.name_ = name_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.finos.fo.Instruments.Instrument) {
          return mergeFrom((org.finos.fo.Instruments.Instrument)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.finos.fo.Instruments.Instrument other) {
        if (other == org.finos.fo.Instruments.Instrument.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.finos.fo.Instruments.Instrument parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.finos.fo.Instruments.Instrument) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.finos.fo.Instrument)
    }

    // @@protoc_insertion_point(class_scope:org.finos.fo.Instrument)
    private static final org.finos.fo.Instruments.Instrument DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.finos.fo.Instruments.Instrument();
    }

    public static org.finos.fo.Instruments.Instrument getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Instrument>
        PARSER = new com.google.protobuf.AbstractParser<Instrument>() {
      @java.lang.Override
      public Instrument parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Instrument(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Instrument> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Instrument> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.finos.fo.Instruments.Instrument getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface InstrumentListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.finos.fo.InstrumentList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
     */
    java.util.List<org.finos.fo.Instruments.Instrument> 
        getInstrumentsList();
    /**
     * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
     */
    org.finos.fo.Instruments.Instrument getInstruments(int index);
    /**
     * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
     */
    int getInstrumentsCount();
    /**
     * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
     */
    java.util.List<? extends org.finos.fo.Instruments.InstrumentOrBuilder> 
        getInstrumentsOrBuilderList();
    /**
     * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
     */
    org.finos.fo.Instruments.InstrumentOrBuilder getInstrumentsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.finos.fo.InstrumentList}
   */
  public  static final class InstrumentList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.finos.fo.InstrumentList)
      InstrumentListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use InstrumentList.newBuilder() to construct.
    private InstrumentList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private InstrumentList() {
      instruments_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private InstrumentList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                instruments_ = new java.util.ArrayList<org.finos.fo.Instruments.Instrument>();
                mutable_bitField0_ |= 0x00000001;
              }
              instruments_.add(
                  input.readMessage(org.finos.fo.Instruments.Instrument.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          instruments_ = java.util.Collections.unmodifiableList(instruments_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.finos.fo.Instruments.internal_static_org_finos_fo_InstrumentList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.finos.fo.Instruments.internal_static_org_finos_fo_InstrumentList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.finos.fo.Instruments.InstrumentList.class, org.finos.fo.Instruments.InstrumentList.Builder.class);
    }

    public static final int INSTRUMENTS_FIELD_NUMBER = 1;
    private java.util.List<org.finos.fo.Instruments.Instrument> instruments_;
    /**
     * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
     */
    public java.util.List<org.finos.fo.Instruments.Instrument> getInstrumentsList() {
      return instruments_;
    }
    /**
     * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
     */
    public java.util.List<? extends org.finos.fo.Instruments.InstrumentOrBuilder> 
        getInstrumentsOrBuilderList() {
      return instruments_;
    }
    /**
     * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
     */
    public int getInstrumentsCount() {
      return instruments_.size();
    }
    /**
     * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
     */
    public org.finos.fo.Instruments.Instrument getInstruments(int index) {
      return instruments_.get(index);
    }
    /**
     * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
     */
    public org.finos.fo.Instruments.InstrumentOrBuilder getInstrumentsOrBuilder(
        int index) {
      return instruments_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < instruments_.size(); i++) {
        output.writeMessage(1, instruments_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < instruments_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, instruments_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.finos.fo.Instruments.InstrumentList)) {
        return super.equals(obj);
      }
      org.finos.fo.Instruments.InstrumentList other = (org.finos.fo.Instruments.InstrumentList) obj;

      boolean result = true;
      result = result && getInstrumentsList()
          .equals(other.getInstrumentsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getInstrumentsCount() > 0) {
        hash = (37 * hash) + INSTRUMENTS_FIELD_NUMBER;
        hash = (53 * hash) + getInstrumentsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.finos.fo.Instruments.InstrumentList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.finos.fo.Instruments.InstrumentList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.finos.fo.Instruments.InstrumentList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.finos.fo.Instruments.InstrumentList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.finos.fo.Instruments.InstrumentList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.finos.fo.Instruments.InstrumentList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.finos.fo.Instruments.InstrumentList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.finos.fo.Instruments.InstrumentList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.finos.fo.Instruments.InstrumentList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.finos.fo.Instruments.InstrumentList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.finos.fo.Instruments.InstrumentList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.finos.fo.Instruments.InstrumentList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.finos.fo.Instruments.InstrumentList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.finos.fo.InstrumentList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.finos.fo.InstrumentList)
        org.finos.fo.Instruments.InstrumentListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.finos.fo.Instruments.internal_static_org_finos_fo_InstrumentList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.finos.fo.Instruments.internal_static_org_finos_fo_InstrumentList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.finos.fo.Instruments.InstrumentList.class, org.finos.fo.Instruments.InstrumentList.Builder.class);
      }

      // Construct using org.finos.fo.Instruments.InstrumentList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getInstrumentsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (instrumentsBuilder_ == null) {
          instruments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          instrumentsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.finos.fo.Instruments.internal_static_org_finos_fo_InstrumentList_descriptor;
      }

      @java.lang.Override
      public org.finos.fo.Instruments.InstrumentList getDefaultInstanceForType() {
        return org.finos.fo.Instruments.InstrumentList.getDefaultInstance();
      }

      @java.lang.Override
      public org.finos.fo.Instruments.InstrumentList build() {
        org.finos.fo.Instruments.InstrumentList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.finos.fo.Instruments.InstrumentList buildPartial() {
        org.finos.fo.Instruments.InstrumentList result = new org.finos.fo.Instruments.InstrumentList(this);
        int from_bitField0_ = bitField0_;
        if (instrumentsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            instruments_ = java.util.Collections.unmodifiableList(instruments_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.instruments_ = instruments_;
        } else {
          result.instruments_ = instrumentsBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.finos.fo.Instruments.InstrumentList) {
          return mergeFrom((org.finos.fo.Instruments.InstrumentList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.finos.fo.Instruments.InstrumentList other) {
        if (other == org.finos.fo.Instruments.InstrumentList.getDefaultInstance()) return this;
        if (instrumentsBuilder_ == null) {
          if (!other.instruments_.isEmpty()) {
            if (instruments_.isEmpty()) {
              instruments_ = other.instruments_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureInstrumentsIsMutable();
              instruments_.addAll(other.instruments_);
            }
            onChanged();
          }
        } else {
          if (!other.instruments_.isEmpty()) {
            if (instrumentsBuilder_.isEmpty()) {
              instrumentsBuilder_.dispose();
              instrumentsBuilder_ = null;
              instruments_ = other.instruments_;
              bitField0_ = (bitField0_ & ~0x00000001);
              instrumentsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getInstrumentsFieldBuilder() : null;
            } else {
              instrumentsBuilder_.addAllMessages(other.instruments_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.finos.fo.Instruments.InstrumentList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.finos.fo.Instruments.InstrumentList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<org.finos.fo.Instruments.Instrument> instruments_ =
        java.util.Collections.emptyList();
      private void ensureInstrumentsIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          instruments_ = new java.util.ArrayList<org.finos.fo.Instruments.Instrument>(instruments_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.finos.fo.Instruments.Instrument, org.finos.fo.Instruments.Instrument.Builder, org.finos.fo.Instruments.InstrumentOrBuilder> instrumentsBuilder_;

      /**
       * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
       */
      public java.util.List<org.finos.fo.Instruments.Instrument> getInstrumentsList() {
        if (instrumentsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(instruments_);
        } else {
          return instrumentsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
       */
      public int getInstrumentsCount() {
        if (instrumentsBuilder_ == null) {
          return instruments_.size();
        } else {
          return instrumentsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
       */
      public org.finos.fo.Instruments.Instrument getInstruments(int index) {
        if (instrumentsBuilder_ == null) {
          return instruments_.get(index);
        } else {
          return instrumentsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
       */
      public Builder setInstruments(
          int index, org.finos.fo.Instruments.Instrument value) {
        if (instrumentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstrumentsIsMutable();
          instruments_.set(index, value);
          onChanged();
        } else {
          instrumentsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
       */
      public Builder setInstruments(
          int index, org.finos.fo.Instruments.Instrument.Builder builderForValue) {
        if (instrumentsBuilder_ == null) {
          ensureInstrumentsIsMutable();
          instruments_.set(index, builderForValue.build());
          onChanged();
        } else {
          instrumentsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
       */
      public Builder addInstruments(org.finos.fo.Instruments.Instrument value) {
        if (instrumentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstrumentsIsMutable();
          instruments_.add(value);
          onChanged();
        } else {
          instrumentsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
       */
      public Builder addInstruments(
          int index, org.finos.fo.Instruments.Instrument value) {
        if (instrumentsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureInstrumentsIsMutable();
          instruments_.add(index, value);
          onChanged();
        } else {
          instrumentsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
       */
      public Builder addInstruments(
          org.finos.fo.Instruments.Instrument.Builder builderForValue) {
        if (instrumentsBuilder_ == null) {
          ensureInstrumentsIsMutable();
          instruments_.add(builderForValue.build());
          onChanged();
        } else {
          instrumentsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
       */
      public Builder addInstruments(
          int index, org.finos.fo.Instruments.Instrument.Builder builderForValue) {
        if (instrumentsBuilder_ == null) {
          ensureInstrumentsIsMutable();
          instruments_.add(index, builderForValue.build());
          onChanged();
        } else {
          instrumentsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
       */
      public Builder addAllInstruments(
          java.lang.Iterable<? extends org.finos.fo.Instruments.Instrument> values) {
        if (instrumentsBuilder_ == null) {
          ensureInstrumentsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, instruments_);
          onChanged();
        } else {
          instrumentsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
       */
      public Builder clearInstruments() {
        if (instrumentsBuilder_ == null) {
          instruments_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          instrumentsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
       */
      public Builder removeInstruments(int index) {
        if (instrumentsBuilder_ == null) {
          ensureInstrumentsIsMutable();
          instruments_.remove(index);
          onChanged();
        } else {
          instrumentsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
       */
      public org.finos.fo.Instruments.Instrument.Builder getInstrumentsBuilder(
          int index) {
        return getInstrumentsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
       */
      public org.finos.fo.Instruments.InstrumentOrBuilder getInstrumentsOrBuilder(
          int index) {
        if (instrumentsBuilder_ == null) {
          return instruments_.get(index);  } else {
          return instrumentsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
       */
      public java.util.List<? extends org.finos.fo.Instruments.InstrumentOrBuilder> 
           getInstrumentsOrBuilderList() {
        if (instrumentsBuilder_ != null) {
          return instrumentsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(instruments_);
        }
      }
      /**
       * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
       */
      public org.finos.fo.Instruments.Instrument.Builder addInstrumentsBuilder() {
        return getInstrumentsFieldBuilder().addBuilder(
            org.finos.fo.Instruments.Instrument.getDefaultInstance());
      }
      /**
       * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
       */
      public org.finos.fo.Instruments.Instrument.Builder addInstrumentsBuilder(
          int index) {
        return getInstrumentsFieldBuilder().addBuilder(
            index, org.finos.fo.Instruments.Instrument.getDefaultInstance());
      }
      /**
       * <code>repeated .org.finos.fo.Instrument instruments = 1;</code>
       */
      public java.util.List<org.finos.fo.Instruments.Instrument.Builder> 
           getInstrumentsBuilderList() {
        return getInstrumentsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.finos.fo.Instruments.Instrument, org.finos.fo.Instruments.Instrument.Builder, org.finos.fo.Instruments.InstrumentOrBuilder> 
          getInstrumentsFieldBuilder() {
        if (instrumentsBuilder_ == null) {
          instrumentsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.finos.fo.Instruments.Instrument, org.finos.fo.Instruments.Instrument.Builder, org.finos.fo.Instruments.InstrumentOrBuilder>(
                  instruments_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          instruments_ = null;
        }
        return instrumentsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.finos.fo.InstrumentList)
    }

    // @@protoc_insertion_point(class_scope:org.finos.fo.InstrumentList)
    private static final org.finos.fo.Instruments.InstrumentList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.finos.fo.Instruments.InstrumentList();
    }

    public static org.finos.fo.Instruments.InstrumentList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<InstrumentList>
        PARSER = new com.google.protobuf.AbstractParser<InstrumentList>() {
      @java.lang.Override
      public InstrumentList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new InstrumentList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<InstrumentList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<InstrumentList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.finos.fo.Instruments.InstrumentList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_finos_fo_Instrument_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_finos_fo_Instrument_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_finos_fo_Instrument_Id_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_finos_fo_Instrument_Id_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_finos_fo_InstrumentList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_finos_fo_InstrumentList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021instruments.proto\022\014org.finos.fo\"\224\001\n\nIn" +
      "strument\022\014\n\004name\030\001 \001(\t\032x\n\002Id\022\016\n\006ticker\030\001" +
      " \001(\t\022\014\n\004ISIN\030\002 \001(\t\022\r\n\005CUSIP\030\003 \001(\t\022\r\n\005SED" +
      "OL\030\004 \001(\t\022\013\n\003RIC\030\005 \001(\t\022\013\n\003BBG\030\006 \001(\t\022\016\n\006PE" +
      "RMID\030\007 \001(\t\022\014\n\004FIGI\030\010 \001(\t\"?\n\016InstrumentLi" +
      "st\022-\n\013instruments\030\001 \003(\0132\030.org.finos.fo.I" +
      "nstrumentB\016\n\014org.finos.fob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_finos_fo_Instrument_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_finos_fo_Instrument_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_finos_fo_Instrument_descriptor,
        new java.lang.String[] { "Name", });
    internal_static_org_finos_fo_Instrument_Id_descriptor =
      internal_static_org_finos_fo_Instrument_descriptor.getNestedTypes().get(0);
    internal_static_org_finos_fo_Instrument_Id_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_finos_fo_Instrument_Id_descriptor,
        new java.lang.String[] { "Ticker", "ISIN", "CUSIP", "SEDOL", "RIC", "BBG", "PERMID", "FIGI", });
    internal_static_org_finos_fo_InstrumentList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_finos_fo_InstrumentList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_finos_fo_InstrumentList_descriptor,
        new java.lang.String[] { "Instruments", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
