// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portfolio.proto

package org.finos.fo;

public final class PortfolioOuterClass {
  private PortfolioOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PositionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.finos.fo.Position)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.org.finos.fo.Instrument instrument = 1;</code>
     */
    boolean hasInstrument();
    /**
     * <code>.org.finos.fo.Instrument instrument = 1;</code>
     */
    org.finos.fo.Instruments.Instrument getInstrument();
    /**
     * <code>.org.finos.fo.Instrument instrument = 1;</code>
     */
    org.finos.fo.Instruments.InstrumentOrBuilder getInstrumentOrBuilder();

    /**
     * <code>int64 holding = 2;</code>
     */
    long getHolding();
  }
  /**
   * Protobuf type {@code org.finos.fo.Position}
   */
  public  static final class Position extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.finos.fo.Position)
      PositionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Position.newBuilder() to construct.
    private Position(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Position() {
      holding_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Position(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              org.finos.fo.Instruments.Instrument.Builder subBuilder = null;
              if (instrument_ != null) {
                subBuilder = instrument_.toBuilder();
              }
              instrument_ = input.readMessage(org.finos.fo.Instruments.Instrument.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(instrument_);
                instrument_ = subBuilder.buildPartial();
              }

              break;
            }
            case 16: {

              holding_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.finos.fo.PortfolioOuterClass.internal_static_org_finos_fo_Position_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.finos.fo.PortfolioOuterClass.internal_static_org_finos_fo_Position_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.finos.fo.PortfolioOuterClass.Position.class, org.finos.fo.PortfolioOuterClass.Position.Builder.class);
    }

    public static final int INSTRUMENT_FIELD_NUMBER = 1;
    private org.finos.fo.Instruments.Instrument instrument_;
    /**
     * <code>.org.finos.fo.Instrument instrument = 1;</code>
     */
    public boolean hasInstrument() {
      return instrument_ != null;
    }
    /**
     * <code>.org.finos.fo.Instrument instrument = 1;</code>
     */
    public org.finos.fo.Instruments.Instrument getInstrument() {
      return instrument_ == null ? org.finos.fo.Instruments.Instrument.getDefaultInstance() : instrument_;
    }
    /**
     * <code>.org.finos.fo.Instrument instrument = 1;</code>
     */
    public org.finos.fo.Instruments.InstrumentOrBuilder getInstrumentOrBuilder() {
      return getInstrument();
    }

    public static final int HOLDING_FIELD_NUMBER = 2;
    private long holding_;
    /**
     * <code>int64 holding = 2;</code>
     */
    public long getHolding() {
      return holding_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (instrument_ != null) {
        output.writeMessage(1, getInstrument());
      }
      if (holding_ != 0L) {
        output.writeInt64(2, holding_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (instrument_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getInstrument());
      }
      if (holding_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, holding_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.finos.fo.PortfolioOuterClass.Position)) {
        return super.equals(obj);
      }
      org.finos.fo.PortfolioOuterClass.Position other = (org.finos.fo.PortfolioOuterClass.Position) obj;

      boolean result = true;
      result = result && (hasInstrument() == other.hasInstrument());
      if (hasInstrument()) {
        result = result && getInstrument()
            .equals(other.getInstrument());
      }
      result = result && (getHolding()
          == other.getHolding());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasInstrument()) {
        hash = (37 * hash) + INSTRUMENT_FIELD_NUMBER;
        hash = (53 * hash) + getInstrument().hashCode();
      }
      hash = (37 * hash) + HOLDING_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getHolding());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.finos.fo.PortfolioOuterClass.Position parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.finos.fo.PortfolioOuterClass.Position parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.finos.fo.PortfolioOuterClass.Position parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.finos.fo.PortfolioOuterClass.Position parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.finos.fo.PortfolioOuterClass.Position parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.finos.fo.PortfolioOuterClass.Position parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.finos.fo.PortfolioOuterClass.Position parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.finos.fo.PortfolioOuterClass.Position parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.finos.fo.PortfolioOuterClass.Position parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.finos.fo.PortfolioOuterClass.Position parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.finos.fo.PortfolioOuterClass.Position parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.finos.fo.PortfolioOuterClass.Position parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.finos.fo.PortfolioOuterClass.Position prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.finos.fo.Position}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.finos.fo.Position)
        org.finos.fo.PortfolioOuterClass.PositionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.finos.fo.PortfolioOuterClass.internal_static_org_finos_fo_Position_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.finos.fo.PortfolioOuterClass.internal_static_org_finos_fo_Position_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.finos.fo.PortfolioOuterClass.Position.class, org.finos.fo.PortfolioOuterClass.Position.Builder.class);
      }

      // Construct using org.finos.fo.PortfolioOuterClass.Position.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (instrumentBuilder_ == null) {
          instrument_ = null;
        } else {
          instrument_ = null;
          instrumentBuilder_ = null;
        }
        holding_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.finos.fo.PortfolioOuterClass.internal_static_org_finos_fo_Position_descriptor;
      }

      @java.lang.Override
      public org.finos.fo.PortfolioOuterClass.Position getDefaultInstanceForType() {
        return org.finos.fo.PortfolioOuterClass.Position.getDefaultInstance();
      }

      @java.lang.Override
      public org.finos.fo.PortfolioOuterClass.Position build() {
        org.finos.fo.PortfolioOuterClass.Position result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.finos.fo.PortfolioOuterClass.Position buildPartial() {
        org.finos.fo.PortfolioOuterClass.Position result = new org.finos.fo.PortfolioOuterClass.Position(this);
        if (instrumentBuilder_ == null) {
          result.instrument_ = instrument_;
        } else {
          result.instrument_ = instrumentBuilder_.build();
        }
        result.holding_ = holding_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.finos.fo.PortfolioOuterClass.Position) {
          return mergeFrom((org.finos.fo.PortfolioOuterClass.Position)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.finos.fo.PortfolioOuterClass.Position other) {
        if (other == org.finos.fo.PortfolioOuterClass.Position.getDefaultInstance()) return this;
        if (other.hasInstrument()) {
          mergeInstrument(other.getInstrument());
        }
        if (other.getHolding() != 0L) {
          setHolding(other.getHolding());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.finos.fo.PortfolioOuterClass.Position parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.finos.fo.PortfolioOuterClass.Position) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private org.finos.fo.Instruments.Instrument instrument_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.finos.fo.Instruments.Instrument, org.finos.fo.Instruments.Instrument.Builder, org.finos.fo.Instruments.InstrumentOrBuilder> instrumentBuilder_;
      /**
       * <code>.org.finos.fo.Instrument instrument = 1;</code>
       */
      public boolean hasInstrument() {
        return instrumentBuilder_ != null || instrument_ != null;
      }
      /**
       * <code>.org.finos.fo.Instrument instrument = 1;</code>
       */
      public org.finos.fo.Instruments.Instrument getInstrument() {
        if (instrumentBuilder_ == null) {
          return instrument_ == null ? org.finos.fo.Instruments.Instrument.getDefaultInstance() : instrument_;
        } else {
          return instrumentBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.finos.fo.Instrument instrument = 1;</code>
       */
      public Builder setInstrument(org.finos.fo.Instruments.Instrument value) {
        if (instrumentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          instrument_ = value;
          onChanged();
        } else {
          instrumentBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.finos.fo.Instrument instrument = 1;</code>
       */
      public Builder setInstrument(
          org.finos.fo.Instruments.Instrument.Builder builderForValue) {
        if (instrumentBuilder_ == null) {
          instrument_ = builderForValue.build();
          onChanged();
        } else {
          instrumentBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.finos.fo.Instrument instrument = 1;</code>
       */
      public Builder mergeInstrument(org.finos.fo.Instruments.Instrument value) {
        if (instrumentBuilder_ == null) {
          if (instrument_ != null) {
            instrument_ =
              org.finos.fo.Instruments.Instrument.newBuilder(instrument_).mergeFrom(value).buildPartial();
          } else {
            instrument_ = value;
          }
          onChanged();
        } else {
          instrumentBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.finos.fo.Instrument instrument = 1;</code>
       */
      public Builder clearInstrument() {
        if (instrumentBuilder_ == null) {
          instrument_ = null;
          onChanged();
        } else {
          instrument_ = null;
          instrumentBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.finos.fo.Instrument instrument = 1;</code>
       */
      public org.finos.fo.Instruments.Instrument.Builder getInstrumentBuilder() {
        
        onChanged();
        return getInstrumentFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.finos.fo.Instrument instrument = 1;</code>
       */
      public org.finos.fo.Instruments.InstrumentOrBuilder getInstrumentOrBuilder() {
        if (instrumentBuilder_ != null) {
          return instrumentBuilder_.getMessageOrBuilder();
        } else {
          return instrument_ == null ?
              org.finos.fo.Instruments.Instrument.getDefaultInstance() : instrument_;
        }
      }
      /**
       * <code>.org.finos.fo.Instrument instrument = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.finos.fo.Instruments.Instrument, org.finos.fo.Instruments.Instrument.Builder, org.finos.fo.Instruments.InstrumentOrBuilder> 
          getInstrumentFieldBuilder() {
        if (instrumentBuilder_ == null) {
          instrumentBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.finos.fo.Instruments.Instrument, org.finos.fo.Instruments.Instrument.Builder, org.finos.fo.Instruments.InstrumentOrBuilder>(
                  getInstrument(),
                  getParentForChildren(),
                  isClean());
          instrument_ = null;
        }
        return instrumentBuilder_;
      }

      private long holding_ ;
      /**
       * <code>int64 holding = 2;</code>
       */
      public long getHolding() {
        return holding_;
      }
      /**
       * <code>int64 holding = 2;</code>
       */
      public Builder setHolding(long value) {
        
        holding_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 holding = 2;</code>
       */
      public Builder clearHolding() {
        
        holding_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.finos.fo.Position)
    }

    // @@protoc_insertion_point(class_scope:org.finos.fo.Position)
    private static final org.finos.fo.PortfolioOuterClass.Position DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.finos.fo.PortfolioOuterClass.Position();
    }

    public static org.finos.fo.PortfolioOuterClass.Position getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Position>
        PARSER = new com.google.protobuf.AbstractParser<Position>() {
      @java.lang.Override
      public Position parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Position(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Position> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Position> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.finos.fo.PortfolioOuterClass.Position getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PortfolioOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.finos.fo.Portfolio)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .org.finos.fo.Position positions = 2;</code>
     */
    java.util.List<org.finos.fo.PortfolioOuterClass.Position> 
        getPositionsList();
    /**
     * <code>repeated .org.finos.fo.Position positions = 2;</code>
     */
    org.finos.fo.PortfolioOuterClass.Position getPositions(int index);
    /**
     * <code>repeated .org.finos.fo.Position positions = 2;</code>
     */
    int getPositionsCount();
    /**
     * <code>repeated .org.finos.fo.Position positions = 2;</code>
     */
    java.util.List<? extends org.finos.fo.PortfolioOuterClass.PositionOrBuilder> 
        getPositionsOrBuilderList();
    /**
     * <code>repeated .org.finos.fo.Position positions = 2;</code>
     */
    org.finos.fo.PortfolioOuterClass.PositionOrBuilder getPositionsOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code org.finos.fo.Portfolio}
   */
  public  static final class Portfolio extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.finos.fo.Portfolio)
      PortfolioOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Portfolio.newBuilder() to construct.
    private Portfolio(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Portfolio() {
      name_ = "";
      positions_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Portfolio(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                positions_ = new java.util.ArrayList<org.finos.fo.PortfolioOuterClass.Position>();
                mutable_bitField0_ |= 0x00000002;
              }
              positions_.add(
                  input.readMessage(org.finos.fo.PortfolioOuterClass.Position.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          positions_ = java.util.Collections.unmodifiableList(positions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.finos.fo.PortfolioOuterClass.internal_static_org_finos_fo_Portfolio_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.finos.fo.PortfolioOuterClass.internal_static_org_finos_fo_Portfolio_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.finos.fo.PortfolioOuterClass.Portfolio.class, org.finos.fo.PortfolioOuterClass.Portfolio.Builder.class);
    }

    public interface IdOrBuilder extends
        // @@protoc_insertion_point(interface_extends:org.finos.fo.Portfolio.Id)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string portfolioId = 1;</code>
       */
      java.lang.String getPortfolioId();
      /**
       * <code>string portfolioId = 1;</code>
       */
      com.google.protobuf.ByteString
          getPortfolioIdBytes();
    }
    /**
     * Protobuf type {@code org.finos.fo.Portfolio.Id}
     */
    public  static final class Id extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:org.finos.fo.Portfolio.Id)
        IdOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Id.newBuilder() to construct.
      private Id(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Id() {
        portfolioId_ = "";
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Id(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                portfolioId_ = s;
                break;
              }
              default: {
                if (!parseUnknownFieldProto3(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.finos.fo.PortfolioOuterClass.internal_static_org_finos_fo_Portfolio_Id_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.finos.fo.PortfolioOuterClass.internal_static_org_finos_fo_Portfolio_Id_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.finos.fo.PortfolioOuterClass.Portfolio.Id.class, org.finos.fo.PortfolioOuterClass.Portfolio.Id.Builder.class);
      }

      public static final int PORTFOLIOID_FIELD_NUMBER = 1;
      private volatile java.lang.Object portfolioId_;
      /**
       * <code>string portfolioId = 1;</code>
       */
      public java.lang.String getPortfolioId() {
        java.lang.Object ref = portfolioId_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          portfolioId_ = s;
          return s;
        }
      }
      /**
       * <code>string portfolioId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getPortfolioIdBytes() {
        java.lang.Object ref = portfolioId_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          portfolioId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getPortfolioIdBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, portfolioId_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getPortfolioIdBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, portfolioId_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof org.finos.fo.PortfolioOuterClass.Portfolio.Id)) {
          return super.equals(obj);
        }
        org.finos.fo.PortfolioOuterClass.Portfolio.Id other = (org.finos.fo.PortfolioOuterClass.Portfolio.Id) obj;

        boolean result = true;
        result = result && getPortfolioId()
            .equals(other.getPortfolioId());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + PORTFOLIOID_FIELD_NUMBER;
        hash = (53 * hash) + getPortfolioId().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static org.finos.fo.PortfolioOuterClass.Portfolio.Id parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.finos.fo.PortfolioOuterClass.Portfolio.Id parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.finos.fo.PortfolioOuterClass.Portfolio.Id parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.finos.fo.PortfolioOuterClass.Portfolio.Id parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.finos.fo.PortfolioOuterClass.Portfolio.Id parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static org.finos.fo.PortfolioOuterClass.Portfolio.Id parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static org.finos.fo.PortfolioOuterClass.Portfolio.Id parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.finos.fo.PortfolioOuterClass.Portfolio.Id parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.finos.fo.PortfolioOuterClass.Portfolio.Id parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static org.finos.fo.PortfolioOuterClass.Portfolio.Id parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static org.finos.fo.PortfolioOuterClass.Portfolio.Id parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static org.finos.fo.PortfolioOuterClass.Portfolio.Id parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(org.finos.fo.PortfolioOuterClass.Portfolio.Id prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code org.finos.fo.Portfolio.Id}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:org.finos.fo.Portfolio.Id)
          org.finos.fo.PortfolioOuterClass.Portfolio.IdOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return org.finos.fo.PortfolioOuterClass.internal_static_org_finos_fo_Portfolio_Id_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return org.finos.fo.PortfolioOuterClass.internal_static_org_finos_fo_Portfolio_Id_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  org.finos.fo.PortfolioOuterClass.Portfolio.Id.class, org.finos.fo.PortfolioOuterClass.Portfolio.Id.Builder.class);
        }

        // Construct using org.finos.fo.PortfolioOuterClass.Portfolio.Id.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          portfolioId_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return org.finos.fo.PortfolioOuterClass.internal_static_org_finos_fo_Portfolio_Id_descriptor;
        }

        @java.lang.Override
        public org.finos.fo.PortfolioOuterClass.Portfolio.Id getDefaultInstanceForType() {
          return org.finos.fo.PortfolioOuterClass.Portfolio.Id.getDefaultInstance();
        }

        @java.lang.Override
        public org.finos.fo.PortfolioOuterClass.Portfolio.Id build() {
          org.finos.fo.PortfolioOuterClass.Portfolio.Id result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public org.finos.fo.PortfolioOuterClass.Portfolio.Id buildPartial() {
          org.finos.fo.PortfolioOuterClass.Portfolio.Id result = new org.finos.fo.PortfolioOuterClass.Portfolio.Id(this);
          result.portfolioId_ = portfolioId_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof org.finos.fo.PortfolioOuterClass.Portfolio.Id) {
            return mergeFrom((org.finos.fo.PortfolioOuterClass.Portfolio.Id)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(org.finos.fo.PortfolioOuterClass.Portfolio.Id other) {
          if (other == org.finos.fo.PortfolioOuterClass.Portfolio.Id.getDefaultInstance()) return this;
          if (!other.getPortfolioId().isEmpty()) {
            portfolioId_ = other.portfolioId_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          org.finos.fo.PortfolioOuterClass.Portfolio.Id parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (org.finos.fo.PortfolioOuterClass.Portfolio.Id) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object portfolioId_ = "";
        /**
         * <code>string portfolioId = 1;</code>
         */
        public java.lang.String getPortfolioId() {
          java.lang.Object ref = portfolioId_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            portfolioId_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string portfolioId = 1;</code>
         */
        public com.google.protobuf.ByteString
            getPortfolioIdBytes() {
          java.lang.Object ref = portfolioId_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            portfolioId_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string portfolioId = 1;</code>
         */
        public Builder setPortfolioId(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          portfolioId_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string portfolioId = 1;</code>
         */
        public Builder clearPortfolioId() {
          
          portfolioId_ = getDefaultInstance().getPortfolioId();
          onChanged();
          return this;
        }
        /**
         * <code>string portfolioId = 1;</code>
         */
        public Builder setPortfolioIdBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          portfolioId_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:org.finos.fo.Portfolio.Id)
      }

      // @@protoc_insertion_point(class_scope:org.finos.fo.Portfolio.Id)
      private static final org.finos.fo.PortfolioOuterClass.Portfolio.Id DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new org.finos.fo.PortfolioOuterClass.Portfolio.Id();
      }

      public static org.finos.fo.PortfolioOuterClass.Portfolio.Id getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Id>
          PARSER = new com.google.protobuf.AbstractParser<Id>() {
        @java.lang.Override
        public Id parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Id(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Id> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Id> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public org.finos.fo.PortfolioOuterClass.Portfolio.Id getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int POSITIONS_FIELD_NUMBER = 2;
    private java.util.List<org.finos.fo.PortfolioOuterClass.Position> positions_;
    /**
     * <code>repeated .org.finos.fo.Position positions = 2;</code>
     */
    public java.util.List<org.finos.fo.PortfolioOuterClass.Position> getPositionsList() {
      return positions_;
    }
    /**
     * <code>repeated .org.finos.fo.Position positions = 2;</code>
     */
    public java.util.List<? extends org.finos.fo.PortfolioOuterClass.PositionOrBuilder> 
        getPositionsOrBuilderList() {
      return positions_;
    }
    /**
     * <code>repeated .org.finos.fo.Position positions = 2;</code>
     */
    public int getPositionsCount() {
      return positions_.size();
    }
    /**
     * <code>repeated .org.finos.fo.Position positions = 2;</code>
     */
    public org.finos.fo.PortfolioOuterClass.Position getPositions(int index) {
      return positions_.get(index);
    }
    /**
     * <code>repeated .org.finos.fo.Position positions = 2;</code>
     */
    public org.finos.fo.PortfolioOuterClass.PositionOrBuilder getPositionsOrBuilder(
        int index) {
      return positions_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      for (int i = 0; i < positions_.size(); i++) {
        output.writeMessage(2, positions_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      for (int i = 0; i < positions_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, positions_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.finos.fo.PortfolioOuterClass.Portfolio)) {
        return super.equals(obj);
      }
      org.finos.fo.PortfolioOuterClass.Portfolio other = (org.finos.fo.PortfolioOuterClass.Portfolio) obj;

      boolean result = true;
      result = result && getName()
          .equals(other.getName());
      result = result && getPositionsList()
          .equals(other.getPositionsList());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getPositionsCount() > 0) {
        hash = (37 * hash) + POSITIONS_FIELD_NUMBER;
        hash = (53 * hash) + getPositionsList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.finos.fo.PortfolioOuterClass.Portfolio parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.finos.fo.PortfolioOuterClass.Portfolio parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.finos.fo.PortfolioOuterClass.Portfolio parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.finos.fo.PortfolioOuterClass.Portfolio parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.finos.fo.PortfolioOuterClass.Portfolio parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.finos.fo.PortfolioOuterClass.Portfolio parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.finos.fo.PortfolioOuterClass.Portfolio parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.finos.fo.PortfolioOuterClass.Portfolio parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.finos.fo.PortfolioOuterClass.Portfolio parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.finos.fo.PortfolioOuterClass.Portfolio parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.finos.fo.PortfolioOuterClass.Portfolio parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.finos.fo.PortfolioOuterClass.Portfolio parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.finos.fo.PortfolioOuterClass.Portfolio prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.finos.fo.Portfolio}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.finos.fo.Portfolio)
        org.finos.fo.PortfolioOuterClass.PortfolioOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.finos.fo.PortfolioOuterClass.internal_static_org_finos_fo_Portfolio_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.finos.fo.PortfolioOuterClass.internal_static_org_finos_fo_Portfolio_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.finos.fo.PortfolioOuterClass.Portfolio.class, org.finos.fo.PortfolioOuterClass.Portfolio.Builder.class);
      }

      // Construct using org.finos.fo.PortfolioOuterClass.Portfolio.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPositionsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        if (positionsBuilder_ == null) {
          positions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          positionsBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.finos.fo.PortfolioOuterClass.internal_static_org_finos_fo_Portfolio_descriptor;
      }

      @java.lang.Override
      public org.finos.fo.PortfolioOuterClass.Portfolio getDefaultInstanceForType() {
        return org.finos.fo.PortfolioOuterClass.Portfolio.getDefaultInstance();
      }

      @java.lang.Override
      public org.finos.fo.PortfolioOuterClass.Portfolio build() {
        org.finos.fo.PortfolioOuterClass.Portfolio result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.finos.fo.PortfolioOuterClass.Portfolio buildPartial() {
        org.finos.fo.PortfolioOuterClass.Portfolio result = new org.finos.fo.PortfolioOuterClass.Portfolio(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        if (positionsBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            positions_ = java.util.Collections.unmodifiableList(positions_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.positions_ = positions_;
        } else {
          result.positions_ = positionsBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.finos.fo.PortfolioOuterClass.Portfolio) {
          return mergeFrom((org.finos.fo.PortfolioOuterClass.Portfolio)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.finos.fo.PortfolioOuterClass.Portfolio other) {
        if (other == org.finos.fo.PortfolioOuterClass.Portfolio.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (positionsBuilder_ == null) {
          if (!other.positions_.isEmpty()) {
            if (positions_.isEmpty()) {
              positions_ = other.positions_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensurePositionsIsMutable();
              positions_.addAll(other.positions_);
            }
            onChanged();
          }
        } else {
          if (!other.positions_.isEmpty()) {
            if (positionsBuilder_.isEmpty()) {
              positionsBuilder_.dispose();
              positionsBuilder_ = null;
              positions_ = other.positions_;
              bitField0_ = (bitField0_ & ~0x00000002);
              positionsBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPositionsFieldBuilder() : null;
            } else {
              positionsBuilder_.addAllMessages(other.positions_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.finos.fo.PortfolioOuterClass.Portfolio parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.finos.fo.PortfolioOuterClass.Portfolio) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<org.finos.fo.PortfolioOuterClass.Position> positions_ =
        java.util.Collections.emptyList();
      private void ensurePositionsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          positions_ = new java.util.ArrayList<org.finos.fo.PortfolioOuterClass.Position>(positions_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.finos.fo.PortfolioOuterClass.Position, org.finos.fo.PortfolioOuterClass.Position.Builder, org.finos.fo.PortfolioOuterClass.PositionOrBuilder> positionsBuilder_;

      /**
       * <code>repeated .org.finos.fo.Position positions = 2;</code>
       */
      public java.util.List<org.finos.fo.PortfolioOuterClass.Position> getPositionsList() {
        if (positionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(positions_);
        } else {
          return positionsBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.finos.fo.Position positions = 2;</code>
       */
      public int getPositionsCount() {
        if (positionsBuilder_ == null) {
          return positions_.size();
        } else {
          return positionsBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.finos.fo.Position positions = 2;</code>
       */
      public org.finos.fo.PortfolioOuterClass.Position getPositions(int index) {
        if (positionsBuilder_ == null) {
          return positions_.get(index);
        } else {
          return positionsBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.finos.fo.Position positions = 2;</code>
       */
      public Builder setPositions(
          int index, org.finos.fo.PortfolioOuterClass.Position value) {
        if (positionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionsIsMutable();
          positions_.set(index, value);
          onChanged();
        } else {
          positionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Position positions = 2;</code>
       */
      public Builder setPositions(
          int index, org.finos.fo.PortfolioOuterClass.Position.Builder builderForValue) {
        if (positionsBuilder_ == null) {
          ensurePositionsIsMutable();
          positions_.set(index, builderForValue.build());
          onChanged();
        } else {
          positionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Position positions = 2;</code>
       */
      public Builder addPositions(org.finos.fo.PortfolioOuterClass.Position value) {
        if (positionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionsIsMutable();
          positions_.add(value);
          onChanged();
        } else {
          positionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Position positions = 2;</code>
       */
      public Builder addPositions(
          int index, org.finos.fo.PortfolioOuterClass.Position value) {
        if (positionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePositionsIsMutable();
          positions_.add(index, value);
          onChanged();
        } else {
          positionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Position positions = 2;</code>
       */
      public Builder addPositions(
          org.finos.fo.PortfolioOuterClass.Position.Builder builderForValue) {
        if (positionsBuilder_ == null) {
          ensurePositionsIsMutable();
          positions_.add(builderForValue.build());
          onChanged();
        } else {
          positionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Position positions = 2;</code>
       */
      public Builder addPositions(
          int index, org.finos.fo.PortfolioOuterClass.Position.Builder builderForValue) {
        if (positionsBuilder_ == null) {
          ensurePositionsIsMutable();
          positions_.add(index, builderForValue.build());
          onChanged();
        } else {
          positionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Position positions = 2;</code>
       */
      public Builder addAllPositions(
          java.lang.Iterable<? extends org.finos.fo.PortfolioOuterClass.Position> values) {
        if (positionsBuilder_ == null) {
          ensurePositionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, positions_);
          onChanged();
        } else {
          positionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Position positions = 2;</code>
       */
      public Builder clearPositions() {
        if (positionsBuilder_ == null) {
          positions_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          positionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Position positions = 2;</code>
       */
      public Builder removePositions(int index) {
        if (positionsBuilder_ == null) {
          ensurePositionsIsMutable();
          positions_.remove(index);
          onChanged();
        } else {
          positionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.finos.fo.Position positions = 2;</code>
       */
      public org.finos.fo.PortfolioOuterClass.Position.Builder getPositionsBuilder(
          int index) {
        return getPositionsFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.finos.fo.Position positions = 2;</code>
       */
      public org.finos.fo.PortfolioOuterClass.PositionOrBuilder getPositionsOrBuilder(
          int index) {
        if (positionsBuilder_ == null) {
          return positions_.get(index);  } else {
          return positionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.finos.fo.Position positions = 2;</code>
       */
      public java.util.List<? extends org.finos.fo.PortfolioOuterClass.PositionOrBuilder> 
           getPositionsOrBuilderList() {
        if (positionsBuilder_ != null) {
          return positionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(positions_);
        }
      }
      /**
       * <code>repeated .org.finos.fo.Position positions = 2;</code>
       */
      public org.finos.fo.PortfolioOuterClass.Position.Builder addPositionsBuilder() {
        return getPositionsFieldBuilder().addBuilder(
            org.finos.fo.PortfolioOuterClass.Position.getDefaultInstance());
      }
      /**
       * <code>repeated .org.finos.fo.Position positions = 2;</code>
       */
      public org.finos.fo.PortfolioOuterClass.Position.Builder addPositionsBuilder(
          int index) {
        return getPositionsFieldBuilder().addBuilder(
            index, org.finos.fo.PortfolioOuterClass.Position.getDefaultInstance());
      }
      /**
       * <code>repeated .org.finos.fo.Position positions = 2;</code>
       */
      public java.util.List<org.finos.fo.PortfolioOuterClass.Position.Builder> 
           getPositionsBuilderList() {
        return getPositionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          org.finos.fo.PortfolioOuterClass.Position, org.finos.fo.PortfolioOuterClass.Position.Builder, org.finos.fo.PortfolioOuterClass.PositionOrBuilder> 
          getPositionsFieldBuilder() {
        if (positionsBuilder_ == null) {
          positionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              org.finos.fo.PortfolioOuterClass.Position, org.finos.fo.PortfolioOuterClass.Position.Builder, org.finos.fo.PortfolioOuterClass.PositionOrBuilder>(
                  positions_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          positions_ = null;
        }
        return positionsBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:org.finos.fo.Portfolio)
    }

    // @@protoc_insertion_point(class_scope:org.finos.fo.Portfolio)
    private static final org.finos.fo.PortfolioOuterClass.Portfolio DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.finos.fo.PortfolioOuterClass.Portfolio();
    }

    public static org.finos.fo.PortfolioOuterClass.Portfolio getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Portfolio>
        PARSER = new com.google.protobuf.AbstractParser<Portfolio>() {
      @java.lang.Override
      public Portfolio parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Portfolio(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Portfolio> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Portfolio> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.finos.fo.PortfolioOuterClass.Portfolio getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_finos_fo_Position_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_finos_fo_Position_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_finos_fo_Portfolio_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_finos_fo_Portfolio_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_finos_fo_Portfolio_Id_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_finos_fo_Portfolio_Id_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017portfolio.proto\022\014org.finos.fo\032\021instrum" +
      "ents.proto\"I\n\010Position\022,\n\ninstrument\030\001 \001" +
      "(\0132\030.org.finos.fo.Instrument\022\017\n\007holding\030" +
      "\002 \001(\003\"_\n\tPortfolio\022\014\n\004name\030\001 \001(\t\022)\n\tposi" +
      "tions\030\002 \003(\0132\026.org.finos.fo.Position\032\031\n\002I" +
      "d\022\023\n\013portfolioId\030\001 \001(\tB\016\n\014org.finos.fob\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.finos.fo.Instruments.getDescriptor(),
        }, assigner);
    internal_static_org_finos_fo_Position_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_finos_fo_Position_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_finos_fo_Position_descriptor,
        new java.lang.String[] { "Instrument", "Holding", });
    internal_static_org_finos_fo_Portfolio_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_finos_fo_Portfolio_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_finos_fo_Portfolio_descriptor,
        new java.lang.String[] { "Name", "Positions", });
    internal_static_org_finos_fo_Portfolio_Id_descriptor =
      internal_static_org_finos_fo_Portfolio_descriptor.getNestedTypes().get(0);
    internal_static_org_finos_fo_Portfolio_Id_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_finos_fo_Portfolio_Id_descriptor,
        new java.lang.String[] { "PortfolioId", });
    org.finos.fo.Instruments.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
